### ISSUE TITLE
EMUELEC SDL 2.26 and higher Segfault due to controllerguid

### ISSUE THREAD

**Issue by Kelvfimer** [ptitSeb/box64#1018]
Hello 

I'm from the tester community of Emuelec and I'm updating from SDL 2.24.2 to higher versions. I notice that SDL2.26 and onwards crashes box64 due to the new CRC functionality. I tested with a xbox360 wireless pad and with a regular wired xbox 360 pad. The pads appear as generic x-box pad

The SDL2 commit that starts to fail is https://github.com/libsdl-org/SDL/commit/3cbfd75d0fb00c8816d2a2523a0be0a86757aff3

If the pad is turnes on it works and the gamr is executed.
Platform
-----------------
The platform used is odroid n2+ . BOX64 has been built using Ubuntu 22.04 WSL2 gcc 12.1, cmake 3.27.5 Emuelec Toolchain for amlogic-ng

Log File
----------------
[emuelec.log](https://github.com/libsdl-org/SDL/files/12848399/emuelec.log)

The issue is only happening with Box64 but it seems related to SDL as the call is within the context of the shovel knight game when asking for the pad. 

However I want to check with Box64 community.

ask
----------------
Understand if it's a bug in SDL or maybe is not retriving the controllerdb file from any path or a Box64 bug. I don't know :)

But I'm sure is related to the controllerids before the seg fault. 

Sdl2 issue report 
https://github.com/libsdl-org/SDL/issues/8372

Thx for your support

**Comment by ptitSeb** [comment]
Ok, I fixed the signature, it should be good to go now.

**Comment by Kelvfimer** [comment]
@ptitSeb  thx for your support. it is still failing on my end 

attached and tested with SDL 2.28.4
[emuelec.log](https://github.com/ptitSeb/box64/files/12860234/emuelec.log)

**Comment by ptitSeb** [comment]
It's with the updated box64? Strange, it should work now. Can you send me the `libsdl2-2.0.so.0` binary so I can test on my side?

**Comment by ptitSeb** [comment]
OOOh, but maybe the game itself is not compatible with that newer SDL2 version? Did you try on x86_64?

**Comment by Kelvfimer** [comment]
@ptitSeb  we are in a new stage of the game :) check the call stack is other 

[emuelec.log](https://github.com/ptitSeb/box64/files/12860980/emuelec.log)

Last calls
9495|0x1020c7e73: Calling pthread_mutex_lock (/usr/lib/libc.so.6)(0x45038D88, 0x0, 0x0, ...) => return 0x0
9495|0x1020ab1c6: Calling ???(/usr/lib/libc.so.6+0x7fb42e3380)(0x461F2768, 0x0, 0x1000, ...) => return 0x1
9495|0x1020ab1c6: Calling ???(/usr/lib/libc.so.6+0x7fb42e3380)(0x461F3768, 0x0, 0x168, ...) => return 0x461F3768
9495|0x1020c7ea3: Calling __pthread_mutex_unlock (/usr/lib/libc.so.6)(0x45038D88, 0x0, 0x46066418, ...) => return 0x0
9495|0x1020c7ea3: Calling __pthread_mutex_unlock (/usr/lib/libc.so.6)(0x46146D88, 0x0, 0x46066418, ...) => return 0x0
9495|0x1020c7aa2: Calling __kernel_gettimeofday (linux-vdso.so.1)(0x1032FFEB0, 0x0, 0x45A, ...) => return 0x0
9495|0x1020c7a42: Calling __kernel_gettimeofday (linux-vdso.so.1)(0x1032FFF20, 0x0, 0x1D0, ...) => return 0x0
9495|0x1020c8a41: Calling snd_pcm_writei (/usr/lib/libasound.so.2)(0x4615A190, 0x461F2768, 0x45A, ...) => return 
9430|0xdcc992: Calling SDL_GameControllerOpen (/usr/lib/libSDL2-2.0.so.0)(0x0, 0x1256AB0, 0x22C, ...) => return 0x4C8CA380
9430|0xdcc9ab: Calling SDL_GameControllerGetJoystick (/usr/lib/libSDL2-2.0.so.0)(0x4C8CA380, 0x1256AB0, 0x22C, ...) => return 0x457B9A10
9430|0xdcc9bb: Calling SDL_JoystickInstanceID (/usr/lib/libSDL2-2.0.so.0)(0x457B9A10, 0x1256AB0, 0x22C, ...) => return 0x0
9430|0xdcc9d0: Calling SDL_GameControllerGetJoystick (/usr/lib/libSDL2-2.0.so.0)(0x4C8CA380, 0x1256AB0, 0x22C, ...) => return 0x457B9A10
9430|0xdcc9e5: Calling SDL_GameControllerNameForIndex (/usr/lib/libSDL2-2.0.so.0)(0x0, 0x1256AB0, 0x22C, ...) => return 0x4576DE20
9430|0xdccde4: Calling SDL_JoystickGetGUID (/usr/lib/libSDL2-2.0.so.0)(0x457B9A10, 0x457B9A10, 0x22C, ...) => return 0x45E65860003
9430|0xdcce01: Calling my2_SDL_GetJoystickGUIDInfo (ShovelKnight)(0x45E65860003, 0x60A000002A1, 0x101FFF81E, ...) => return 
9495|0x1020c7e73: Calling pthread_mutex_lock (/usr/lib/libc.so.6)(0x46146D88, 0x0, 0x0, ...) => return 0x0
NativeBT: ShovelKnight() [0x348b0114]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb4422670]
NativeBT: /usr/lib/libSDL2-2.0.so.0(+0x536cc) [0x7fb3b736cc]
NativeBT: ShovelKnight(my2_SDL_GetJoystickGUIDInfo+0x50) [0x3506d46c]
NativeBT: ShovelKnight() [0x34e7c07c]
NativeBT: ShovelKnight() [0x34884764]
NativeBT: [0x7fac09e1e8]
EmulatedBT: ??? [0x50980]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN18ycControllerDevice18FindControllerTypeEPKcP13_SDL_Joystick+31) [0xdcce01]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN18ycControllerDevice17RescanControllersEv+1ed) [0xdcc9fd]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN18ycControllerDevice6UpdateEf+24) [0xdcb4a4]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN7ycInput6UpdateEf+3b) [0xde8a9b]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN6ycMain10UpdateGameEv+512) [0xdf67b2]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_ZN6ycMain3RunEv+50) [0xdf6240]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(main+339) [0x913629]
EmulatedBT: ??? [0x30080]
EmulatedBT: /storage/roms/ports/shovelknight/64/ShovelKnight(_start+29) [0x474830]

Maybe it rings any bell to you @ptitSeb

**Comment by ptitSeb** [comment]
Some issue with `SDL_GetJoystickGUIDInfo` function call.
TBH, if the game was compiled for a SDL 2.26 it will use SDL_GetJoystickGUIDInfo with only 3 pointer, as that was the old API. But with 2.28 it use a 4th pointer, that will be "garbage" and will certainly crash when accessed.

This is the old version: https://github.com/bminor/SDL/blob/master/src/joystick/SDL_joystick.c#L1606
Here is new version: https://fossies.org/linux/SDL2/src/joystick/SDL_joystick.c line 1880

Changing the signature of a function without changing it's name is bad :( Not much box can do there.

**Comment by Kelvfimer** [comment]
Ok per your statement the issue is in the game itself . Am I right? thx

**Comment by ptitSeb** [comment]
I would say the game cannot run with too recent SDL2 yes. And I think you would have the same behaviour if you run this game with a 2.28 SDL2 on native x86_64 too.

**Comment by Kelvfimer** [comment]
Think so too .

Thx for you super support @ptitSeb so much appreciated :)

**Comment by ptitSeb** [comment]
Hey, I would like to make sure of something, can you run
```bash
readelf -aW /PATH/TO/ShovelKnight | grep SDL_GetJoystickGUIDInfo
```

I want to see if, maybe, there is a symbol version somewhere (I don't think there, I haven't seen anything about version symbol in SDL2), just to be sure.

This is issue anoy me, and I would like to find a workaround (by, somehow, detecting the version of SDL2 the program was linked with)

**Comment by miwasp** [comment]
> /home/xxx> readelf -aW ShovelKnight| grep SDL_GetJoystickGUIDInfo
00000000011f7828  0000012900000007 R_X86_64_JUMP_SLOT     0000000000000000 SDL_GetJoystickGUIDInfo + 0
   297: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SDL_GetJoystickGUIDInfo
 28970: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SDL_GetJoystickGUIDInfo>

My understanding is that SDL_GetJoystickGUIDInfo was a private function in SDL2 <= 2.24. Nevertheless it was used in Shovelknight.
In SDL2 versions >= 2.26 the function was made public and a parameter was added, which results in the crash og Shovelknight.

**Comment by miwasp** [comment]
That would be really great.

Interestingly the 32bit version of Shovelknight started with box86 does not have this problem!?

**Comment by Kelvfimer** [comment]
64 bit

readelf -aW ShovelKnight | grep SDL_GetJoystickGUIDInfo
00000000011f7828  0000012900000007 R_X86_64_JUMP_SLOT     0000000000000000 SDL_GetJoystickGUIDInfo + 0
   297: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SDL_GetJoystickGUIDInfo
 28970: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SDL_GetJoystickGUIDInfo

**Comment by ptitSeb** [comment]
Ok, I have added the workaround.
I will add it to box86 too, because I think it's still happening there but work because the ABI is different and the args is on the stack, wich is probably a NULL pointer by "luck" there

**Comment by Kelvfimer** [comment]
Hello @ptitSeb 

on my side new commit x64 it's failing same behaviour

[emuelec.log](https://github.com/ptitSeb/box64/files/12869596/emuelec.log)

**Comment by ptitSeb** [comment]
from the log, I can see your `box64.box64rc`, that should be in  `/etc` is outdated.

it reads:
```
Params database has 13 entries
```
But latest version has 28 entries.
And I don't see the message that `BOX64_SDL2_JGUID=1 is applied` (something like that).

**Comment by ptitSeb** [comment]
If you have no `box64.box64rc` at all, it will use a default file in-memory. And this version embedded in box64 have the ShovelKnight parameter.

**Comment by miwasp** [comment]
Ah ok, then its working as designed for me.
Kelvfimer is still testing...

**Comment by MSHectorCM** [comment]
@ptitSeb sorry it works :) . My fault testing.

**Comment by ptitSeb** [comment]
Ah good :)

**Comment by Kelvfimer** [comment]
fixed thx again for your mega support and help @ptitSeb

**Comment by miwasp** [comment]
Just one small remark:
In box86 i have to explicitly set BOX86_SDL2_JGUID=1, otherwise i get
> 7586|0x8d0a97f: Unimplemented Opcode (46) 65 B8 02 77 65 42 00 00

box64 and box86 just behave differently here.

**Comment by ptitSeb** [comment]
Yes, box86 doesn't have the in-memory default box86.box86rc in case none is found in the system. I may backport this to box86 in the future, but not sure when...
You can copy `box86.box64rc` in `/etc` if you prefer not to have to use the env. var.

**Comment by miwasp** [comment]
I know of at least one other project that uses box86 in combination with Shovelknight. They also don't use any rc-file and will run across this when they bump box86. Additionally in all those projects /etc is read-only, so the rc-file must be copied at compile time.

But its not really a problem, just a thing i noticed.

Thanks for all your help.

**Comment by ptitSeb** [comment]
Thanks for the info. I'll do the in-memory rcfile on box86 sonner then...

Note that the rcfile mecanism on box use 2 files. One is in `/etc/box64.box64rc` and is the reference one (and is supposed to only change rarely). And a second on is `~/.box64rc`. This one is in the home of the user and contains local setup b the end-user. Settings in the `~/.box64rc` overrides the one in `/etc/box64.box64rc`
