### ISSUE TITLE
RimWorld 1.2/1.3 - Random crashes

### ISSUE THREAD

**Issue by KweezyCode** [ptitSeb/box64#110]
Mono path[0] = '/home/kweezy/Desktop/RimWorld/RimWorldLinux_Data/Managed'
Mono config path = '/home/kweezy/Desktop/RimWorld/RimWorldLinux_Data/MonoBleedingEdge/etc'
0xa04860a0: Stack is corrupted, aborting
==== CPU Registers ====
RAX=207119f200bbe6c3 RCX=0000000000000000 RDX=0000ffffb393d440 RBX=0000ffffb393d3b0 RSP=0000ffffb393d398 FLAGS=--S--PC
RBP=0000ffffb393d448 RSI=0000ffffb393d448 RDI=0000ffffb393d3b0  R8=0000000000000001  R9=0000000000000010 
R10=0000000000000000 R11=0000000000000000 R12=0000ffffb393d440 R13=00000000a2cde790 R14=0000ffffb393d498 
R15=00000000a2cde780 RIP=00000000a04a6913 
======== Stack ========
Stack is from FFFFB393D448 to FFFFB393D398
Old IP: A04860A0
LIBGL: Shuting down
59973|0xa04a9000: Unimplemented Opcode (00) F0 1F EA A0 00 00 00 00 90 72 49 A0 00 00 00

**Comment by dinchamion** [comment]
Same for me, on a Pi4 8GB with Ubuntu MATE.

**Comment by ptitSeb** [comment]
The opocde liste is an invalid one. The issue os not the opecode, but the "Stack is corrupted" message that happened before.

I have fixed some the stack corruption error, but not all it seems.

**Comment by KweezyPlay** [comment]
problem still exists
[dump.txt](https://github.com/ptitSeb/box64/files/7278878/dump.txt)
[dump1.txt](https://github.com/ptitSeb/box64/files/7278879/dump1.txt)

**Comment by ptitSeb** [comment]
Ok
Relevent part on dump1 is
```
29907|0xffff969ffd5a: Calling my_pthread_mutex_init (/usr/local/bin/box64)(0xFFFF96D4E960, 0x0, 0x1, ...) => return 0x0
29907|0xffff96a16db8: Calling __libc_calloc (/lib/aarch64-linux-gnu/libc.so.6)(0x1, 0x10, 0x1, ...) => return 0x8C61CCF0
29907|0xffff96a0eba8: Calling sem_init (/lib/aarch64-linux-gnu/libpthread.so.0)(0x8C61AC30, 0x0, 0x0, ...) => return 0x0
29907|0xffff96a0e8f9: Calling pthread_setspecific (/lib/aarch64-linux-gnu/libpthread.so.0)(0x19, 0x8C61ABD0, 0x0, ...) => return 0x0
29907|0xffff96a11c41: Calling my_pthread_attr_init (/usr/local/bin/box64)(0xFFFFB03AB3E0, 0xFFFFB03AB470, 0x0, ...) => return 0x0
29907|0xffff96a11c7b: Calling pthread_self (/lib/aarch64-linux-gnu/libc.so.6)(0xFFFFB03AB3E0, 0xFFFFB03AB470, 0x0, ...) => return 0xFFFFB08BB870
29907|0xffff96a11c86: Calling pthread_getattr_np (/lib/aarch64-linux-gnu/libc.so.6)(0xFFFFB08BB870, 0xFFFFB03AB3E0, 0x0, ...) => return 0x0
29907|0xffff96a11cc9: Calling my_pthread_attr_getstack (/usr/local/bin/box64)(0xFFFFB03AB3E0, 0xFFFFB03AB478, 0xFFFFB03AB470, ...) => return 0x0
29907|0xffff96a11d06: Calling my_pthread_attr_destroy (/usr/local/bin/box64)(0xFFFFB03AB3E0, 0xFFFFB03AB478, 0xFFFFB03AB470, ...) => return 0x0
29907|0xffff96a11d50: Calling my___stack_chk_fail (/usr/local/bin/box64)(0xFFFFB03AB3E0, 0xFFFFB03AB478, 0xFFFFB03AB470, ...) =>0x8a0350a0: Stack is corrupted, aborting
==== CPU Registers ====
RAX=10d5e6b23c171300 RCX=0000ffff96a0e8dd RDX=0000ffffb03ab470 RBX=0000ffffb03ab3e0 RSP=0000ffffb03ab3c8 FLAGS=--S--PC
RBP=0000ffffb03ab478 RSI=0000ffffb03ab478 RDI=0000ffffb03ab3e0  R8=0000000000000001  R9=0000000000000010 
R10=0000000000000000 R11=0000000000000000 R12=0000ffffb03ab470 R13=000000008c60dc70 R14=0000ffffb03ab4c8 
R15=000000008c60dc60 RIP=000000008a055913 
======== Stack ========
Stack is from FFFFB03AB478 to FFFFB03AB3C8
Old IP: 8A0350A0
 return 0x10D5E6B23C171300
 return 0x0
End of X86 run (0x8a036130), RIP=0xffff96a11d50, Stack=0xffffb03ab3d0, unimp=0, emu->fork=0, emu->uc_link=(nil), emu->quit=1
```
Seems to be related to the `my_pthread_attr_getstack(...)` call. I'll check later.

**Comment by mogery** [comment]
> do you need log?

Yup. STDOUT, Player.log, and a reading from `cat /proc/$(pgrep RimWorld)/maps` while the loading screen is present.

**Comment by mogery** [comment]
> Have been trying it a few times. Got it running twice, but otherwise crash:
> 
> `RimWorld 1.3.3117 rev664 Error loading needed lib /home/dinchamion/apps/rimworld/data/noarch/game/RimWorldLinux_Data/Managed/System.Xml.Linq.dll.so Warning: Cannot dlopen("/home/dinchamion/apps/rimworld/data/noarch/game/RimWorldLinux_Data/Managed/System.Xml.Linq.dll.so"/0x8605c320, 101) Error loading needed lib /home/dinchamion/apps/rimworld/data/noarch/game/RimWorldLinux_Data/Managed/mono/aot-cache/amd64/System.Xml.Linq.dll.so Warning: Cannot dlopen("/home/dinchamion/apps/rimworld/data/noarch/game/RimWorldLinux_Data/Managed/mono/aot-cache/amd64/System.Xml.Linq.dll.so"/0x86c2e9a0, 101) double free or corruption (fasttop) 18495|0x64952d8a: Unimplemented Opcode (DF) FE 97 60 02 40 F9 5C DD FE 97 E3 FF FF 17 1F`
> 
> [rimworld-crash.txt](https://github.com/ptitSeb/box64/files/7368280/rimworld-crash.txt)
> 
> Using BOX64_LOG=2 outright makes it hang without even getting to the loading screen.
> 
> Gonna try to test it a bit more, and if I luck into making it run, will try to get some logs.
> 
> ![Screenshot at 2021-10-18 20-02-45](https://user-images.githubusercontent.com/7282347/137802638-1c298643-cded-4130-9216-74af59894016.png) ![Screenshot at 2021-10-18 20-13-57](https://user-images.githubusercontent.com/7282347/137802644-cdb1be87-e883-4b7c-bd63-8c07822459cf.png)

I'm pretty sure it doesn't hang, preload just gets slowed down by all the writing. It'd be awesome if you could get me a Player.log with LOG=2.

**Comment by ptitSeb** [comment]
So it's probably a timing issue if detailled logs makes it run.

**Comment by mogery** [comment]
> about an hour or so

Hmm. Ok. That's an issue for trying over and over again. I'll think about how to approach this.

**Comment by KweezyPlay** [comment]
i got it running only once, can't run game anymore for no reason. i am using Ubuntu 21 (the latest)

**Comment by dinchamion** [comment]
Current testing status:
* starting with no log setting or 1: game launches and crashes on the loading screen (couldn't yet get it running again)
* with log level 2 or 3 it creates a 1.6+gb log file for both Player.log and /tmp/rimworld_log_1000 and just hangs there pretty indefinitely. CPU and memory load is negligible, so my guess is that it freezes and doesn't do anything. (But I'm not sure. I'll let it run for a couple of hours later today.)

I've uploaded a player.log from the crash (with no loglevel) and the "idle" state I killed after a while (with loglevel 3): https://www.dropbox.com/sh/bhkan3u8t115hhw/AADlce1rifWNYzGilarGtvoca?dl=0 

I don't know how to do a memory map, you'll need to be slow and patient with me. :-P

**Comment by ptitSeb** [comment]
I reduce PROT_DYNAREC value to have protection tracking done on `uint8_t` instead of `uint32_t`. I have seen any linux `PROT_*` flags higher the 0x04 (READ, WRITE, EXEC...) so I did that reduction to save some space.

**Comment by bbbruni** [comment]
Please post instructions for WheezyZ on how to disable compiler optimizations in that github thread so that he can try to avoid SIGBUS.

**Comment by KweezyPlay** [comment]
no way, new rimworld is only 64 bit. alpha and beta were 32/64

**Comment by bbbruni** [comment]
@KweezyPlay
@dinchamion 
@mogery 

Please retest.
Sebastien reworked custommem.c on November 5 in https://github.com/ptitSeb/box64/commit/f73e4193f032713529e26c4537e5fac44147c040

**Comment by dinchamion** [comment]
Still crashing unfortunately, with 

`Debug info from gdb:

* Assertion: should not be reached at class-accessors.c:73

FillBlock at 0x6a140 triggered a segfault, cancelling
*** stack smashing detected ***: terminated`

[rimworld_log_1000.log](https://github.com/ptitSeb/box64/files/7534296/rimworld_log_1000.log)

**Comment by ptitSeb** [comment]
Yes, it does crash randomly for me. But now it launch, most of the time, for me. It start like in 4 out 5 times, and I'm able to play for somet time. But after a few autosaves, it eventualy crash.

**Comment by bbbruni** [comment]
> Yes, it does crash randomly for me. But now it launch, most of the time, for me. It start like in 4 out 5 times, and I'm able to play for somet time. But after a few autosaves, it eventualy crash.

I saw you made `memprot` variable in custommem.c volatile. I'm a Java/C# dev and know volatile is a very tricky keyword serving as a half memory barrier in multhreading purposes in those languages. In C, volatile is usually is a way to forbid optimisations.

I am not sure I understand why you decided to use `volatile`.
Do you want an effect of memory barriers?
Or want to prevent a simultaneous access of multiple threads to `memprot` variable?

**Comment by ptitSeb** [comment]
the `volatile` is there to prevent C compiler to do optimisation, because that variable may be changed be another thread.
The issue here is that many thread are going on, with a JIT in the middle that is tranforming C# bytecode to assembly, and all this need to be handle by box64 own Dynarec, that need to track what block of code needs to be discarded (because the code itself as changed), and was code can (or must) be keeped.
Multi-Thread + JIT is tricky to emulate with a Dynarec...

**Comment by bbbruni** [comment]
> the `volatile` is there to prevent C compiler to do optimisation, because that variable may be changed be another thread. The issue here is that many thread are going on, with a JIT in the middle that is tranforming C# bytecode to assembly, and all this need to be handle by box64 own Dynarec, that need to track what block of code needs to be discarded (because the code itself as changed), and was code can (or must) be keeped. Multi-Thread + JIT is tricky to emulate with a Dynarec...

Maybe it's worth inserting more trace instructions in cutommem source?

From dinchamion's log, it's unclear in which of transformations mentioned by you (I mean, in which lock) a segfault took place.

**Comment by ptitSeb** [comment]
I'm not sure were to search. That's the issue with multi-task problem, they don't trigger where the root cause is.
Maybe I'll try to add some Memory Barrier later, like with box86. Maybe that will help...

**Comment by ptitSeb** [comment]
I have added the memory barrier. You can retry @dinchamion

**Comment by dinchamion** [comment]
Looks to be starting up reliably now. :-)

Need to do more testing and actually playing it more, but so far so good. (The errors on startup are probably due to my savegame being vanilla without expansions.)

![Screenshot at 2021-11-16 20-49-34](https://user-images.githubusercontent.com/7282347/142063636-2bc57e3a-fa46-4e71-b524-3330968f03b7.png)
![Screenshot at 2021-11-16 20-49-42](https://user-images.githubusercontent.com/7282347/142063641-0223b606-081a-4675-83ee-de2e4e11f2f8.png)

**Comment by bbbruni** [comment]
> Looks to be starting up reliably now. :-)
> 
> Need to do more testing and actually playing it more, but so far so good. (The errors on startup are probably due to my savegame being vanilla without expansions.)

Could you please say if you had a crash at 6a1b9e050a488cb5b2e1217fd3a01e484c3d7bb7?

**Comment by KweezyPlay** [comment]
RimWorld 1.3 still loads with random crashes, and it doesn't load at all with mods Harmony and RimThreaded (just freezes, check screenshot)
![Screenshot from 2021-11-22 13-11-53](https://user-images.githubusercontent.com/36813920/142843191-ae328d50-40c6-4926-a724-6340b2f343b8.png)

**Comment by KweezyPlay** [comment]
Rimworld without mods:
[Player.log](https://github.com/ptitSeb/box64/files/7580489/Player.log)

**Comment by bbbruni** [comment]
Maximal thread-safety would include the following.
1. Ideally, every method which uses a writeable (modifiable) variable which value can be accessed by multiple threads, must be synchronized (protect its body with a lock itself or be protected by its caller). 
I.e. 
getProtection, nextFree, maxFree, find47bitBlock, etc. 
2. introduce asserts for thread-interleaving in functions that access those variables in the beginning and in the end of every such function. Mono source is full of them: https://github.com/mono/mono/blob/main/mono/mini/aot-compiler.c
I.e. 
```
void updateProtection(uintptr_t addr, uintptr_t size, uint32_t prot)
{
    assert(_memprot_cannot_be_greater_than_10000_before_UpdateProtection_starts_in_any_thread-interleaving_state);
    const uintptr_t idx = (addr>>MEMPROT_SHIFT);
    const uintptr_t end = ((addr+size-1)>>MEMPROT_SHIFT);
    pthread_mutex_lock(&mutex_prot);
    for (uintptr_t i=idx; i<=end; ++i) {
        uint32_t dyn=(memprot[i]&PROT_DYNAREC);
        if(dyn && (prot&PROT_WRITE))    // need to remove the write protection from this block
            mprotect((void*)(i<<MEMPROT_SHIFT), 1<<MEMPROT_SHIFT, prot&~PROT_WRITE);
        memprot[i] = prot|dyn;
    }
    pthread_mutex_unlock(&mutex_prot);
    assert(_memprot_cannot_be_greater_than_10000_after_UpdateProtection_finishes_in_any_thread-interleaving_state);
}
```
I don't know real invariants for memprot, so 10000 is arbitrary here.

3. every asm code fragment which needs memory barriers should be protected by locks as well

@ptitSeb 
I don't understand why e.g. getProtection, nextFree are not protected by locks.
Could you explain it, please?

**Comment by ptitSeb** [comment]
> I don't understand why e.g. getProtection, nextFree are not protected by locks.
> Could you explain it, please?

It's speed concern: I designed the structure so they can be accessed lock-free. Every function that only read the datas are lock free, but function that write are behind a mutex, to simplify handling.

The issue with RimWorld is that it also use lock-free mecanism, and it translate poorly on arm because of the low-level difference on how memory works between x86 and arm.

**Comment by bbbruni** [comment]
How about introducing asserts to track invariant violations (e.g., for memory mapping)?

**Comment by ptitSeb** [comment]
What do you have in mind precisely?

**Comment by bbbruni** [comment]
As I can grasp from crash logs here, the problem is that dynablocks overwrite memory areas being used by some other entities. (Correct me if I'm wrong)
Invariant could include checking for that memory range is not used by anything.

**Comment by ptitSeb** [comment]
> As I can grasp from crash logs here, the problem is that dynablocks overwrite memory areas being used by some other entities. 

Yes, probably, but what could be happening is that a dynablock has been invalidated (because some x86 code as been changed), and the memory block is recycled for a next block, but another thread is executing that block of code, because some parts are still valid? Automatic jump to a block that as been invalidated is disabled (the jumptable is set to default), but jump inside the block can still happens, so a thread migh be in a loop somewhere...
That's my theory

> (Correct me if I'm wrong) Invariant could include checking for that memory range is not used by anything.

If my theory is correct, the assert will show nothing, because a thread is just executing a block.

**Comment by ptitSeb** [comment]
What I mean is there are 2 kind of jumps when building a block: the jump that stays in the block, and the jump that goes outside of the block.
The jump (or `call` or `ret`) that goes outside of the block use a "jump table". It takes that jump table value and just jump there. The address can either be an entry point for another block, or the the "Dynarec Linker" that will check if a block is availble, ask to build a build if needed, and jump that the block or exit the dynarec to run the interpretor.
For the jump inside the block, it's just a regular jump to the arm code equivalent to the x86 address....

**Comment by bbbruni** [comment]
It's still unclear what is meant under that troublesome loop...

**Comment by KweezyPlay** [comment]
> It's still unclear what is meant under that troublesome loop... From the current description, there are no visible problems.

do you mean there is no problem?

**Comment by bbbruni** [comment]
> > It's still unclear what is meant under that troublesome loop... From the current description, there are no visible problems.
> 
> do you mean there is no problem?

I mean there is no clear definition for RimWorld problem so far.

**Comment by bbbruni** [comment]
@ptitSeb

It looks like many mutex blocks `pthread_mutex_lock ... pthread_mutex_unlock` may be replaced with `__transaction_atomic { ... }` thanks to gcc libitm so that to make debugging easier.

libitm already works in RasberryOS: https://forums.raspberrypi.com/viewtopic.php?t=287488

In theory, atomic transactions in libitm have no deadlocks. One of multiple conflicting threads wins, the others just roll back their execution by letting the first thread complete its job. Later, the others try to restart.

So the freeze mentioned in https://github.com/ptitSeb/box64/issues/110#issuecomment-975364012 should be much easier to debug and understand (if caused by deadlock).

What do you think about introducing a special debug mode and replacing
`pthread_mutex_lock(&mutex_blocks);`
with something like
```
    #ifdef LIBITM
    __transaction_atomic {
    #else
    pthread_mutex_lock(&mutex_blocks);
    #endif
```
?

**Comment by ptitSeb** [comment]
I'll look into it later: I'll see if it can be beneficial to have optional libitm use.

**Comment by bbbruni** [comment]
You was so fast answer ;P
Are you familiar with libitm?

**Comment by KweezyPlay** [comment]
any news?

**Comment by ptitSeb** [comment]
On what?

**Comment by ptitSeb** [comment]
RimWorld work on my side. Can this ticket be closed?

**Comment by ptitSeb** [comment]
RimWorld is stable on my side, closing the issue.
