### ISSUE TITLE
issue while trying to run the powder toy

### ISSUE THREAD

**Issue by USMP-lancer** [ptitSeb/box64#126]
this might be a similar problem to issue #113(since it has error messages that are almost one to one)
when i try running it errors out really fast
here is the error message
>  Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
> Box64 with Dynarec v0.1.5 289deb3 built on Oct  8 2021 21:27:32
> Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
> Using default BOX64_PATH: ./:bin/
> Counted 35 Env var
> Looking for powder
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libssl.so.1
> Using native(wrapped) libcrypto.so.1
> Using native(wrapped) libm.so.6
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux-x86-64.so.2
> Using native(wrapped) librt.so.1
> Error: PltResolver: Symbol OPENSSL_load_builtin_modules(ver 6: OPENSSL_load_builtin_modules@OPENSSL_1_1_0) not > > found, cannot apply R_X86_64_JUMP_SLOT 0x7d3c6c6608 (0x7d3baad0d6)
(side note, i omitted the directory as its not important to this)
(side side note, ask if you dont know what the powder toy is)

**Comment by USMP-lancer** [comment]
it will be awhile before i respond as im typing this late at night and am going to head to bed lmao

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
This function is not wrapped yet:

https://github.com/search?q=repo%3AptitSeb%2Fbox64%20OPENSSL_load_builtin_modules&type=code

It's probably still an issue. I've noticed a few other applications needing more wrapped OpenSSL functions, too.
