### ISSUE TITLE
Unable to launch war thunder

### ISSUE THREAD

**Issue by AmirDahan** [ptitSeb/box64#1376]
Attempting to run war thunder's ``launcher`` gets stuck or crashes with this error:
```
Error: PltResolver: Symbol gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 (0x7fff021e05a6) in /mnt/nas/WarThunder/libsciter-gtk.so

(launcher:1820): Gtk-WARNING **: 00:04:57.051: drawing failure for widget 'GtkDrawingArea': cairo_restore() without matching cairo_save()

(launcher:1820): Gtk-WARNING **: 00:04:57.051: drawing failure for widget 'GtkWindow': cairo_restore() without matching cairo_save()
Error: PltResolver: Symbol gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 (0x7fff021e05a6) in /mnt/nas/WarThunder/libsciter-gtk.so
```

**Comment by NotToDisturb** [comment]
I can replicate, see trace:
```console
disturbo@disturbo-switch:~/.local/share/Steam/steamapps/common/War Thunder$ ./launcher
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 PageSize:4096 Running on Cortex-A57 with 4 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 81 entries
Box64 with Dynarec v0.3.1 d10a0784 built on Jul 11 2024 06:38:39
BOX64: Detected 48bits at least of address space
Counted 83 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for ./launcher
Rename process to "launcher"
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
Warning, CALL to 0x0 at 0x7253bc (0x7253bb)
Warning, CALL to 0x0 at 0x724416 (0x724415)
Warning, CALL to 0x0 at 0x72443b (0x72443a)
Warning, CALL to 0x0 at 0x72454b (0x72454a)
Warning, CALL to 0x0 at 0x72457c (0x72457b)
Warning, CALL to 0x0 at 0x7239cc (0x7239cb)
Warning, CALL to 0x0 at 0x723a0b (0x723a0a)
Warning, CALL to 0x0 at 0x723a47 (0x723a46)
Warning, CALL to 0x0 at 0x723d66 (0x723d65)
Warning, CALL to 0x0 at 0x723b39 (0x723b38)
Warning, CALL to 0x0 at 0x7244ef (0x7244ee)
Warning, CALL to 0x0 at 0x723e7d (0x723e7c)
Warning, CALL to 0x0 at 0x723ead (0x723eac)
Warning, CALL to 0x0 at 0x723edc (0x723edb)
Warning, CALL to 0x0 at 0x723d66 (0x723d65)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 PageSize:4096 Running on Cortex-A57 with 4 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 81 entries
Box64 with Dynarec v0.3.1 d10a0784 built on Jul 11 2024 06:38:39
BOX64: Detected 48bits at least of address space
Counted 83 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for /home/disturbo/.local/share/Steam/steamapps/common/War Thunder/gaijin_selfupdater
argv[1]="-appid"
argv[2]="WarThunderLauncherLinux"
argv[3]="-localversion"
argv[4]="1.0.3.15"
argv[5]="-execpath"
argv[6]="launcher"
argv[7]="-notify_user_about_failure"
Rename process to "gaijin_selfupdater"
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
Warning, CALL to 0x0 at 0x7b66ab (0x7b66aa)
Warning, CALL to 0x0 at 0x4eb4fc (0x4eb4fb)
Warning, CALL to 0x0 at 0x4ea556 (0x4ea555)
Warning, CALL to 0x0 at 0x4ea57b (0x4ea57a)
Warning, CALL to 0x0 at 0x4ea68b (0x4ea68a)
Warning, CALL to 0x0 at 0x4ea6bc (0x4ea6bb)
Warning, CALL to 0x0 at 0x4e9b0c (0x4e9b0b)
Warning, CALL to 0x0 at 0x4e9b4b (0x4e9b4a)
Warning, CALL to 0x0 at 0x4e9b87 (0x4e9b86)
Warning, CALL to 0x0 at 0x4e9ea6 (0x4e9ea5)
Warning, CALL to 0x0 at 0x4e9c79 (0x4e9c78)
Warning, CALL to 0x0 at 0x4ea62f (0x4ea62e)
Warning, CALL to 0x0 at 0x4ea62f (0x4ea62e)
Warning, CALL to 0x0 at 0x4e9fbd (0x4e9fbc)
Warning, CALL to 0x0 at 0x4e9fed (0x4e9fec)
Warning, CALL to 0x0 at 0x4ea01c (0x4ea01b)
Warning, CALL to 0x0 at 0x4e9ea6 (0x4e9ea5)
Using emulated /home/disturbo/.local/share/Steam/steamapps/common/War Thunder/libsciter-gtk.so
Using native(wrapped) libcairo.so.2

(process:5137): Gtk-WARNING **: 00:05:45.337: Locale not supported by C library.
        Using the fallback 'C' locale.
Warning, CALL to 0x0 at 0x80dca6 (0x80dca5)
Warning, CALL to 0x0 at 0x711dd2 (0x711dd1)
Warning, CALL to 0x0 at 0x70fa92 (0x70fa91)
Warning, CALL to 0x0 at 0x70fe62 (0x70fe61)
Warning, CALL to 0x0 at 0x711b61 (0x711b60)
Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Warning, recreating YMM11 on non empty slot ymm6Error: PltResolver: Symbol  gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 (0x7fff021e05a6) in /home/disturbo/.local/share/Steam/steamapps/common/War Thunder/libsciter-gtk.so (local_maplib=0x37062650, global maplib=0x36c26410, deepbind=0)

(launcher:5137): Gtk-WARNING **: 00:05:55.236: drawing failure for widget 'GtkDrawingArea': cairo_restore() without matching cairo_save()

(launcher:5137): Gtk-WARNING **: 00:05:55.236: drawing failure for widget 'GtkWindow': cairo_restore() without matching cairo_save()
Error: PltResolver: Symbol  gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 (0x7fff021e05a6) in /home/disturbo/.local/share/Steam/steamapps/common/War Thunder/libsciter-gtk.so (local_maplib=0x37062650, global maplib=0x36c26410, deepbind=0)
Error: PltResolver: Symbol  gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 (0x7fff021e05a6) in /home/disturbo/.local/share/Steam/steamapps/common/War Thunder/libsciter-gtk.so (local_maplib=0x37062650, global maplib=0x36c26410, deepbind=0)
Warning, CALL to 0x0 at 0x711f40 (0x711f3f)
Warning, CALL to 0x0 at 0x70cbb1 (0x70cbb0)
Warning, CALL to 0x0 at 0x70cbb1 (0x70cbb0)
Warning, CALL to 0x0 at 0x70c673 (0x70c672)
Segmentation fault (core dumped)```

**Comment by System64fumo** [comment]
Update:
I got bored today and tried to run the game without the launcher
I get a different error now:
```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Blizzard-M2 Avalanche-M2 with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 90 entries
Box64 with Dynarec v0.3.1 f7c93b68 built on Sep 30 2024 12:54:33
BOX64: Detected 48bits at least of address space
Counted 23 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for ./linux64/aces
Rename process to "aces"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libresolv.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
Warning, CALL to 0x0 at 0x4106bd0 (0x4106bcf)
Warning, CALL to 0x0 at 0x4106bef (0x4106bee)
Warning, CALL to 0x0 at 0x1c77a50 (0x1c77a4f)
Warning, CALL to 0x0 at 0x1c77a72 (0x1c77a71)
Warning, CALL to 0x0 at 0x1c77b27 (0x1c77b26)
Warning, CALL to 0x0 at 0x1c77b27 (0x1c77b26)
Warning, CALL to 0x0 at 0x1c780af (0x1c780ae)
Warning, CALL to 0x0 at 0x1c7706d (0x1c7706c)
Warning, CALL to 0x0 at 0x1c771b4 (0x1c771b3)
Warning, CALL to 0x0 at 0x1c771f3 (0x1c771f2)
Warning, CALL to 0x0 at 0x1c7722f (0x1c7722e)
Warning, CALL to 0x0 at 0x1c77366 (0x1c77365)
Using emulated /mnt/nas/WarThunder/linux64/easyanticheat_x64.so
Using emulated linux64/libsteam_api.so
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/home/amir/.steam/sdk64/steamclient.so
with error:
Cannot dlopen("/home/amir/.steam/sdk64/steamclient.so"/0xfffff7cae770, 2)

[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/amir/.steam/sdk64/steamclient.so
Warning, CALL to 0x0 at 0x1c7778b (0x1c7778a)
Warning, CALL to 0x0 at 0x3551504 (0x3551503)
Using native(wrapped) libvulkan.so.1
Error loading needed lib libXrandr.so
Warning: Cannot dlopen("libXrandr.so"/0x5c0fdcf, 1)
Warning, CALL to 0x0 at 0x51b0bac (0x51b0bab)
Warning, CALL to 0x0 at 0x51afd2c (0x51afd2b)
Warning, CALL to 0x0 at 0x51afe6b (0x51afe6a)
Warning, CALL to 0x0 at 0x51afea7 (0x51afea6)
Warning, CALL to 0x0 at 0x51afe6b (0x51afe6a)
Warning, CALL to 0x0 at 0x51afea7 (0x51afea6)
Warning, CALL to 0x0 at 0x1c7747d (0x1c7747c)
Warning, CALL to 0x0 at 0x1c774ad (0x1c774ac)
Warning, CALL to 0x0 at 0x1c774dc (0x1c774db)
Warning, CALL to 0x0 at 0x1c77366 (0x1c77365)
Warning, CALL to 0x0 at 0x1d9e4cd (0x1d9e4cc)
Error loading needed lib libxkbfile.so
Warning: Cannot dlopen("libxkbfile.so"/0x5c0aba6, 1)
Using native(wrapped) libudev.so.1
Warning, CALL to 0x0 at 0x51b0a56 (0x51b0a55)
Warning, CALL to 0x0 at 0x51b0a85 (0x51b0a84)
Sigfault/Segbus while quitting, exiting silently
```

It would still crash/not launch if you provided the x86_64 libs for libXrandr and libxkbfile

**Comment by System64fumo** [comment]
Update, Just got some better hardware to test this on and i got further, Now it gets stuck on `[BOX64] Using emulated /mnt/nas/games/WarThunder/linux64/BEClient_x64.so`

**Comment by System64fumo** [comment]
Hey @ptitSeb, Should this issue be closed since you told me you're not working on games with anticheat?
Unless there are plans to eventually support them?

**Comment by ptitSeb** [comment]
I'm focussing more on DRM for now. But it's quite close.... So, it's up to you.

**Comment by System64fumo** [comment]
Humm, Well if it's close then i suppose this can stay, I can wait i suppose.
Would love to use box64 for WarThunder,
FEX is a little slow and occasionally locks up..

**Comment by auggeythecat** [comment]
> Update, Just got some better hardware to test this on and i got further, Now it gets stuck on `[BOX64] Using emulated /mnt/nas/games/WarThunder/linux64/BEClient_x64.so`

I'm having the same issue. Let me know if you find a work-around. (or if it gets fixed <3 ptitSeb)

**Comment by System64fumo** [comment]
Update as of 20/10/2025

Launching `./linux64/aces` results in
<details>
<summary>Log</summary>

```
[BOX64] Box64 arm64 v0.3.9 e3cd3e834 with Dynarec built on Oct 20 2025 15:31:45
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 45 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
[BOX64] Looking for ./linux64/aces
[BOX64] Rename process to "aces"
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libresolv.so.2
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Error loading needed lib libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Error loading needed lib libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Error loading one of needed lib
[BOX64] Error: Loading needed libs in elf ./linux64/aces
```

</details>

Despite `ls -l /usr/lib/{libstdc++.so.6,libgcc_s.so.1}` showing:
```
-rw-r--r-- 1 root root 723912 Sep 27 12:45 /usr/lib/libgcc_s.so.1
lrwxrwxrwx 1 root root     19 Sep 27 12:45 /usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.34
```


Allow missing libs shows:

<details>
<summary>Log</summary>

```
[BOX64] Box64 arm64 v0.3.9 e3cd3e834 with Dynarec built on Oct 20 2025 15:31:45
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 46 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
[BOX64] Looking for ./linux64/aces
[BOX64] BOX64ENV: Variables overridden:
	BOX64_ALLOWMISSINGLIBS=1
[BOX64] Rename process to "aces"
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libresolv.so.2
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Error loading needed lib libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Error loading needed lib libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Error loading one of needed lib
[BOX64] Error: Global Symbol _ZTISt12out_of_range not found, cannot apply R_X86_64_GLOB_DAT @0x8868f80 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZTVSt12system_error not found, cannot apply R_X86_64_GLOB_DAT @0x8868f90 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZTVSt13runtime_error not found, cannot apply R_X86_64_GLOB_DAT @0x8868fb0 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZTVSt11logic_error not found, cannot apply R_X86_64_GLOB_DAT @0x8868fc0 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZNSt12system_errorD1Ev not found, cannot apply R_X86_64_GLOB_DAT @0x8868fc8 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZNSt12out_of_rangeD1Ev not found, cannot apply R_X86_64_GLOB_DAT @0x8868fd0 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: Global Symbol _ZTVSt12out_of_range not found, cannot apply R_X86_64_GLOB_DAT @0x8868fd8 ((nil)) in /mnt/data/games/WarThunder/linux64/aces
[BOX64] Error: PltResolver: Symbol  __cxa_guard_acquire(optver 12: __cxa_guard_acquire@CXXABI_1.3) not found, cannot apply R_X86_64_JUMP_SLOT 0x8869298 (0x40a536) in /mnt/data/games/WarThunder/linux64/aces (local_maplib=(nil), global maplib=0x6b1dd380, deepbind=0)
[BOX64] 18341|SIGSEGV @0xffffaab862cc (???(0xffffaab862cc)) (x64pc=0x2ef4fa4/"/mnt/data/games/WarThunder/linux64/aces + 0x2af4fa4", rsp=0xffffab48f560, stack=0xffffaac90000:0xffffab490000 own=(nil) fp=0xffffab48f5e0), for accessing (nil) (code=1/prot=0), db=0xffffaab8636b(0xffffaab862b0:0xffffaab86403/0x2ef4f93:0x2ef4fb0//mnt/data/games/WarThunder/linux64/aces + 0x2af4f93:clean, hash:dde90bb3/dde90bb3) handler=(nil)
RAX:0x0000000000000002 RCX:0x0000000000000000 RDX:0x0000000000000000 RBX:0x0000000000000002 
RSP:0x0000ffffab48f560 RBP:0x0000ffffab48f5b0 RSI:0x0000ffffab48f618 RDI:0x0000000000000000 
 R8:0xfffffffffffffff8  R9:0x0000000000000000 R10:0x0000000006efc32b R11:0x0000000000000000 
R12:0x0000ffffab48f618 R13:0x0000000000000001 R14:0x0000ffffab48f618 R15:0x0000000000000001 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
RSP-0x20:0x0000000000000050 RSP-0x18:0x0000000000765822 RSP-0x10:0x0000000000000000 RSP-0x08:0x0000ffffab48f570
RSP+0x00:0x00000002ab48f5a0 RSP+0x08:0x0000000000420280 RSP+0x10:0x0000000000000000 RSP+0x18:0x0000000000420230 x64opcode=48 8B 07 89 DE 48 C1 E6 (opcode=f940022a)
Segmentation fault         BOX64_ALLOWMISSINGLIBS=1 ./linux64/aces
```

</details>

Sorry for constantly checking in/nagging about this.. 😅

**Comment by ptitSeb** [comment]
@System64fumo how did you install box64? libgcc_s.so is a C++ library and so the x64 version needs to be used. A version is installed if you build from sources (same for libstdc++). Else, you can use the `box64-bundle-x86-libs.sh` script (from box64 repo) to install a version.

Without thos libs, it willcertainly not run, even with ALLOW_MISSING.

**Comment by System64fumo** [comment]
@ptitSeb i installed box64 from the AUR with yay -S box64-git

**Comment by ptitSeb** [comment]
what about the other stuffs from my message?

**Comment by System64fumo** [comment]
Box64 already provides `/usr/lib/box64-x86_64-linux-gnu/libstd++.so.6` on my system..

**Comment by ptitSeb** [comment]
and `libgcc_s.so.1` ?

**Comment by System64fumo** [comment]
That too, All the expected libraries are installed.

**Comment by System64fumo** [comment]
@ptitSeb Sorry forgot to ping you, Any ideas?

**Comment by ptitSeb** [comment]
This folder `/usr/lib/box64-x86_64-linux-gnu/` should be used by box64, when searching for lis. So it should find the x64version of those library.

Are you sure the libraries in that folders are correct? can you `file` them?

**Comment by System64fumo** [comment]
Seems fine to me

`file /usr/lib/box64-x86_64-linux-gnu/*`
```
/usr/lib/box64-x86_64-linux-gnu/libcrypto.so.1.0.0: ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=368cd85099880298d2a393a5fc53e4cf4c3ce941, stripped
/usr/lib/box64-x86_64-linux-gnu/libcrypto.so.1.1:   ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=c1418e16a283d787c446f341dd8282afe69f504d, stripped
/usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1:      ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=cd1854e1bd86fa4913521ae6857417c96feb6706, stripped
/usr/lib/box64-x86_64-linux-gnu/libmbedcrypto.so.3: symbolic link to libmbedcrypto.so.7
/usr/lib/box64-x86_64-linux-gnu/libmbedcrypto.so.7: ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=63c0ae260627cbd14d913daf13ff69c111319316, stripped
/usr/lib/box64-x86_64-linux-gnu/libmbedtls.so.12:   symbolic link to libmbedtls.so.14
/usr/lib/box64-x86_64-linux-gnu/libmbedtls.so.14:   ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=ca84cce822a2e7116c9c7117671261a0c95d3bd3, stripped
/usr/lib/box64-x86_64-linux-gnu/libmbedx509.so.0:   symbolic link to libmbedx509.so.1
/usr/lib/box64-x86_64-linux-gnu/libmbedx509.so.1:   ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=b46e209e098088abcdc9eeb7f7ecfaeb80e6746d, stripped
/usr/lib/box64-x86_64-linux-gnu/libpng12.so.0:      ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=9151d1f493ccf2d5c175f31b2685e62db80b2c9d, stripped
/usr/lib/box64-x86_64-linux-gnu/libssl.so.1.0.0:    ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=fdd2575dd587162e06c803dd28375dad7d7f1abb, stripped
/usr/lib/box64-x86_64-linux-gnu/libssl.so.1.1:      ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=019ee6cafe365130eb96b675acab4b9f92fc3f16, stripped
/usr/lib/box64-x86_64-linux-gnu/libstdc++.so.5:     ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, stripped
/usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6:     ELF 64-bit LSB shared object, no machine, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=ab1b320aee6702c149c94e588317d8f66b7ab97a, stripped
/usr/lib/box64-x86_64-linux-gnu/libunwind.so.8:     ELF 64-bit LSB shared object, no machine, version 1 (SYSV), dynamically linked, BuildID[sha1]=dbd50d23f0d2cec93bd2154478e352c8b9c32d34, stripped
```

**Comment by ptitSeb** [comment]
no machine?? that's odd.
On my side, I have
../x64lib/libstdc++.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=ab1b320aee6702c149c94e588317d8f66b7ab97a, stripped

**Comment by ptitSeb** [comment]
probably a limitation of your file

Yet, that doesn't explain why it will not pick this lib

You should launch with BOX64_LOG=2 to get better log.

**Comment by System64fumo** [comment]
@ptitSeb Here's the output of BOX64_LOG=2:
```
[BOX64] Box64 arm64 v0.3.9 e3cd3e834 with Dynarec built on Oct 20 2025 15:31:45
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Setting up canary (for Stack protector) at FS:0x28, value:91314800
[BOX64] Counted 46 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
[BOX64] Looking for ./linux64/aces
[BOX64]  Env[00]: BOX64_LOG=2
[BOX64]  Env[01]: SHELL=/usr/bin/bash
[BOX64]  Env[02]: COLORTERM=truecolor
[BOX64]  Env[03]: HYPRLAND_CMD=Hyprland
[BOX64]  Env[04]: _JAVA_AWT_WM_NONEREPARENTING=1
[BOX64]  Env[05]: HISTCONTROL=ignoreboth:erasedups
[BOX64]  Env[06]: GNOME_DESKTOP_SESSION_ID=yadayada
[BOX64]  Env[07]: XDG_BACKEND=wayland
[BOX64]  Env[08]: HISTSIZE=
[BOX64]  Env[09]: ELECTRON_OZONE_PLATFORM_HINT=wayland
[BOX64]  Env[10]: XDG_SEAT=seat0
[BOX64]  Env[11]: PWD=/mnt/data/games/WarThunder
[BOX64]  Env[12]: LOGNAME=amir
[BOX64]  Env[13]: QT_QPA_PLATFORMTHEME=qt6ct
[BOX64]  Env[14]: XDG_SESSION_TYPE=wayland
[BOX64]  Env[15]: MOTD_SHOWN=pam
[BOX64]  Env[16]: HOME=/home/amir
[BOX64]  Env[17]: LANG=C.UTF-8
[BOX64]  Env[18]: _JAVA_AWT_WM_NONREPARENTING=1
[BOX64]  Env[19]: XDG_CURRENT_DESKTOP=Hyprland
[BOX64]  Env[20]: WAYLAND_DISPLAY=wayland-1
[BOX64]  Env[21]: QT_QPA_PLATFORM=wayland;xcb
[BOX64]  Env[22]: MOZ_DISABLE_RDD_SANDBOX=1
[BOX64]  Env[23]: XDG_SESSION_CLASS=user
[BOX64]  Env[24]: TERM=xterm-256color
[BOX64]  Env[25]: USER=amir
[BOX64]  Env[26]: HYPRLAND_INSTANCE_SIGNATURE=cfac27251af5df4352f747c4539ea9f65450f05a_1761243199_952277608
[BOX64]  Env[27]: DISPLAY=:0
[BOX64]  Env[28]: GSK_RENDERER=cairo
[BOX64]  Env[29]: SHLVL=2
[BOX64]  Env[30]: MOZ_ENABLE_WAYLAND=1
[BOX64]  Env[31]: ICECC_VERSION=/mnt/nas/server/cluster/icecream/native-arm64.tar.gz,riscv64:/mnt/nas/server/cluster/icecream/riscv-to-aarch64.tar.gz,x86_64:/mnt/nas/server/cluster/icecream/x86_64-to-aarch64.tar.gz
[BOX64]  Env[32]: MOZ_USE_XINPUT2=1
[BOX64]  Env[33]: XDG_VTNR=1
[BOX64]  Env[34]: XDG_SESSION_ID=c1
[BOX64]  Env[35]: WINEDEBUG=-all
[BOX64]  Env[36]: XDG_RUNTIME_DIR=/run/user/1000
[BOX64]  Env[37]: DEBUGINFOD_URLS=https://debuginfod.artixlinux.org 
[BOX64]  Env[38]: PATH=/usr/lib/icecream/libexec/icecc/bin:/home/amir/.local/bin:/usr/lib/icecream/libexec/icecc/bin:/home/amir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[BOX64]  Env[39]: DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-enTAp1sSaG,guid=7fea29bdbf7113c1b0f1850668fa703f
[BOX64]  Env[40]: MAIL=/var/spool/mail/amir
[BOX64]  Env[41]: _JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on
-Dswing.aatext=true
-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
[BOX64]  Env[42]: OLDPWD=/home/amir
[BOX64]  Env[43]: BOX64_CPUNAME=Cortex-A520
[BOX64]  Env[44]: MANGOHUD_CONFIG=legacy_layout=0,custom_text_center=Box64 arm64 v0.3.9 e3cd3e834,gpu_stats=1,cpu_stats=1,fps=1,frame_timing=1
[BOX64]  Env[45]: _=./linux64/aces
[BOX64] BOX64ENV: Variables overridden:
	BOX64_LOG=2
[BOX64] Read 32 Section header
[BOX64] Read 12 Program header
[BOX64] Loading Sections Table String (idx = 31)
[BOX64] Loading SymTab Strings (idx = 0)
[BOX64] Loading SymTab (idx = 0)
[BOX64] Loading Dynamic (idx = 24)
[BOX64] The DT_INIT is at address 0x40a000
[BOX64] The DT_FINI is at address 0x6ed844c
[BOX64] The DT_INIT_ARRAY is at address 0x88639f0
[BOX64] The DT_INIT_ARRAYSZ is 1832
[BOX64] The DT_FINI_ARRAY is at address 0x8867330
[BOX64] The DT_FINI_ARRAYSZ is 1
[BOX64] The DT_GNU_HASH is at address 0x400340
[BOX64] The DT_VERNEED is at address 0x406458
[BOX64] The DT_VERNEEDNUM is 7
[BOX64] RelA Table @0x406678 (0x2b8/0x18)
[BOX64] PLT Table @0x406930 (type=7 0x34c8/0x18)
[BOX64] The GOT.PLT Table is at address 0x8869000
[BOX64] The GOT Table is at address 0x8868f78..0x8868fe8
[BOX64] The PLT Table is at address 0x40a020..0x40c360
[BOX64] The .gnu.version is at address 0x405f88
[BOX64] The .text is at address 0x40c400, and is 111984714 big
[BOX64] The .eh_frame section is at address 0x7cc0408..0x88603b0
[BOX64] The .eh_frame_hdr section is at address 0x79fb7ec
[BOX64] Loading DynSym Strings (idx = 6)
[BOX64] Loading DynSym (idx = 5)
[BOX64] Adding "/mnt/data/games/WarThunder/linux64/aces" as #0 in elf collection
[BOX64] Elf Addr(v/p)=0x400000/0x400000 Memsize=0x87f6098 (align=0x1000)
[BOX64] Elf Stack Memsize=1048576 (align=16)
[BOX64] Elf TLS Memsize=2640 (align=16)
[BOX64] Pre-allocated 0x87f6098 byte at 0x400000 for /mnt/data/games/WarThunder/linux64/aces
[BOX64] Delta of (nil) (vaddr=0x400000) for Elf "/mnt/data/games/WarThunder/linux64/aces"
[BOX64] Mmaping 0x9df8(0xa000) bytes @0x400000 with prot 1 for Elf "/mnt/data/games/WarThunder/linux64/aces"
[BOX64] Mmaping 0x6ace455(0x6acf000) bytes @0x40a000 with prot 5 for Elf "/mnt/data/games/WarThunder/linux64/aces"
[BOX64] Mmaping 0x1988beb(0x1989000) bytes @0x6ed9000 with prot 1 for Elf "/mnt/data/games/WarThunder/linux64/aces"
[BOX64] Allocating 0x395000 (0x8863000/0x392a68) bytes @0x8863000, will read 0x9e3d0 @0x8863630 for Elf "/mnt/data/games/WarThunder/linux64/aces"
[BOX64] Loading TLS block #8 @0x3c958eb0 (0x3b8/0xa48)
[BOX64] Rename process to "aces"
[BOX64] Calc stack size, based on 1 elf(s)
[BOX64] Stack is @0xffff8e8d0000 size=0x800000 align=0x10
[BOX64] Allocate a new X86_64 Emu, with RIP=(nil) and Stack=0xffff8e8d0000/0x800000
[BOX64] Setup X86_64 Emu
[BOX64] Grabbing R_X86_64_COPY Relocation(s) in advance for /mnt/data/games/WarThunder/linux64/aces
[BOX64]  Adding unique _ZTVSt15basic_streambufIcSt11char_traitsIcEE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867be0 sz=128
[BOX64]  Adding unique _ZTVSt18basic_stringstreamIcSt11char_traitsIcESaIcEE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867c60 sz=120
[BOX64]  Adding unique _ZTVN10__cxxabiv120__si_class_type_infoE (ver:12/CXXABI_1.3 veropt) with offert=0x8867ce0 sz=88
[BOX64]  Adding unique in6addr_any (ver:2/GLIBC_2.2.5 veropt) with offert=0x8867d40 sz=16
[BOX64]  Adding unique _ZTTSt18basic_stringstreamIcSt11char_traitsIcESaIcEE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867d60 sz=80
[BOX64]  Adding unique _ZTVN10__cxxabiv117__class_type_infoE (ver:12/CXXABI_1.3 veropt) with offert=0x8867dc0 sz=88
[BOX64]  Adding unique _ZTVSt9bad_alloc (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867e20 sz=40
[BOX64]  Adding unique _ZTVSt15basic_stringbufIcSt11char_traitsIcESaIcEE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867e60 sz=128
[BOX64]  Adding unique _ZTVSt9basic_iosIcSt11char_traitsIcEE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8867ee0 sz=32
[BOX64]  Adding unique stderr (ver:2/GLIBC_2.2.5 veropt) with offert=0x8901a08 sz=8
[BOX64]  Adding unique _ZNSs4_Rep20_S_empty_rep_storageE (ver:9/GLIBCXX_3.4 veropt) with offert=0x8901a40 sz=32
[BOX64]  Adding unique stdout (ver:2/GLIBC_2.2.5 veropt) with offert=0x8901a60 sz=8
[BOX64]  Adding unique stdin (ver:2/GLIBC_2.2.5 veropt) with offert=0x8901a00 sz=8
[BOX64]  Adding unique __timezone (ver:2/GLIBC_2.2.5 veropt) with offert=0x8901a20 sz=8
[BOX64]  Adding unique __environ (ver:2/GLIBC_2.2.5 veropt) with offert=0x8901a28 sz=8
[BOX64] Prepending path "/mnt/data/games/WarThunder/linux64" to BOX64_LD_LIBRARY_PATH
[BOX64] Trying to add "libpthread.so.0" to maplib
[BOX64] Trying to load "libpthread.so.0"
[BOX64] Simplified name is "libpthread.so.0"
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Trying to add "libresolv.so.2" to maplib
[BOX64] Trying to load "libresolv.so.2"
[BOX64] Simplified name is "libresolv.so.2"
[BOX64] Using native(wrapped) libresolv.so.2
[BOX64] Trying to add "libdl.so.2" to maplib
[BOX64] Trying to load "libdl.so.2"
[BOX64] Simplified name is "libdl.so.2"
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Trying to add "librt.so.1" to maplib
[BOX64] Trying to load "librt.so.1"
[BOX64] Simplified name is "librt.so.1"
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Trying to add "libX11.so.6" to maplib
[BOX64] Trying to load "libX11.so.6"
[BOX64] Simplified name is "libX11.so.6"
[BOX64] Adding AutomaticBridge for 0xffff8e6405c0 to 0x30050000
[BOX64] Adding AutomaticBridge for 0xffff8e6405a0 to 0x30050020
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Trying to add "libxcb.so.1" to maplib
[BOX64] Trying to load "libxcb.so.1"
[BOX64] Simplified name is "libxcb.so.1"
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Trying to add "libXau.so.6" to maplib
[BOX64] Trying to load "libXau.so.6"
[BOX64] Simplified name is "libXau.so.6"
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Trying to add "libXdmcp.so.6" to maplib
[BOX64] Trying to load "libXdmcp.so.6"
[BOX64] Simplified name is "libXdmcp.so.6"
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Trying to add "libstdc++.so.6" to maplib
[BOX64] Trying to load "libstdc++.so.6"
[BOX64] Simplified name is "libstdc++.so.6"
[BOX64] Faillure to create lib => fail
[BOX64] Error loading needed lib libstdc++.so.6
[BOX64] Trying to add "libm.so.6" to maplib
[BOX64] Trying to load "libm.so.6"
[BOX64] Simplified name is "libm.so.6"
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Trying to add "libgcc_s.so.1" to maplib
[BOX64] Trying to load "libgcc_s.so.1"
[BOX64] Simplified name is "libgcc_s.so.1"
[BOX64] Faillure to create lib => fail
[BOX64] Error loading needed lib libgcc_s.so.1
[BOX64] Trying to add "libc.so.6" to maplib
[BOX64] Trying to load "libc.so.6"
[BOX64] Simplified name is "libc.so.6"
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Trying to add "ld-linux-x86-64.so.2" to maplib
[BOX64] Trying to load "ld-linux-x86-64.so.2"
[BOX64] Simplified name is "ld-linux-x86-64.so.2"
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Trying to add "libpthread.so.0" to maplib
[BOX64] Already present in maplib => success
[BOX64] Trying to add "libdl.so.2" to maplib
[BOX64] Already present in maplib => success
[BOX64] Trying to add "libutil.so.1" to maplib
[BOX64] Trying to load "libutil.so.1"
[BOX64] Simplified name is "libutil.so.1"
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Trying to add "librt.so.1" to maplib
[BOX64] Already present in maplib => success
[BOX64] Trying to add "libbsd.so.0" to maplib
[BOX64] Trying to load "libbsd.so.0"
[BOX64] Simplified name is "libbsd.so.0"
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Created lib and added to maplib => success
[BOX64] Error loading one of needed lib
[BOX64] Error: Loading needed libs in elf ./linux64/aces
[BOX64] 2359|Free a X86_64 Emu (0x3c951170)
```

**Comment by System64fumo** [comment]
I decided to sanity check this, I ran `yay -S box64-git` and waited for it to finish.
Then tried to launch 7z (x86_64), Did not work, Same error
So i tried `LD_LIBRARY_PATH=/usr/lib/box64-x86_64-linux-gnu box64 ./7zz`, Same error
Tried again with `BOX64_LD_LIBRARY_PATH=/usr/lib/box64-x86_64-linux-gnu box64 ./7zz`, Same error

Not sure what went wrong with box64 as of late but it doesn't seem to work at all on arch?
I decided to download the debian package and copy over the files aaaand
That worked?

No idea why, how, or what happened here.

Regardless i tried running `BOX64_LOG=2 box64 ./linux/aces` and noticed it getting stuck in a loop and never actually launches:

[log.txt.gz](https://github.com/user-attachments/files/23255312/log.txt.gz)

@ptitSeb if you could have a look that would be greatly appreciated.

Let me know if i should open another issue to track this weird library problem on arch. (Or in my case artix)

**Comment by ptitSeb** [comment]
I would prefer the Arch issue to be a new ticket.

**Comment by System64fumo** [comment]
Wait this is fixed now?
Have i missed the commit that fixed this?

**Comment by LukeShortCloud** [comment]
I must have misunderstood. The Arch Linux library issue has been addressed but not necessarily this one. Could you retest with the latest build of Box64?

**Comment by System64fumo** [comment]
Will re test shortly though i highly doubt this would ever get fixed..

**Comment by System64fumo** [comment]
The Launcher still crashes:
```
box64 ./launcher
[BOX64] Box64 arm64 v0.4.1 57e87b4ee with Dynarec built on Jan  9 2026 00:25:42
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 50 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
[BOX64] Looking for ./launcher
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] BOX64ENV: Variables overridden:
	BOX64_MALLOC_HACK=2
[BOX64] Rename process to "launcher"
[BOX64] Using native(wrapped) libXrandr.so.2
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Using native(wrapped) libXext.so.6
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libXrender.so.1
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libgtk-3.so.0
[BOX64] Using native(wrapped) libgdk-3.so.0
[BOX64] Using native(wrapped) libgobject-2.0.so.0
[BOX64] Using native(wrapped) libglib-2.0.so.0
[BOX64] Using native(wrapped) libgio-2.0.so.0
[BOX64] Using native(wrapped) libgmodule-2.0.so.0
[BOX64] Using native(wrapped) libgdk_pixbuf-2.0.so.0
[BOX64] Using native(wrapped) libpangocairo-1.0.so.0
[BOX64] Using native(wrapped) libpango-1.0.so.0
[BOX64] Using native(wrapped) libcairo.so.2
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Warning, CALL to 0x0 at 0x73308c (0x73308b)
[BOX64] Warning, CALL to 0x0 at 0x732057 (0x732056)
[BOX64] Warning, CALL to 0x0 at 0x73207e (0x73207d)
[BOX64] Warning, CALL to 0x0 at 0x732057 (0x732056)
[BOX64] Warning, CALL to 0x0 at 0x73207e (0x73207d)
[BOX64] Warning, CALL to 0x0 at 0x7321db (0x7321da)
[BOX64] Warning, CALL to 0x0 at 0x73220c (0x73220b)
[BOX64] Warning, CALL to 0x0 at 0x73155b (0x73155a)
[BOX64] Warning, CALL to 0x0 at 0x73159a (0x731599)
[BOX64] Warning, CALL to 0x0 at 0x7315d6 (0x7315d5)
[BOX64] Warning, CALL to 0x0 at 0x731986 (0x731985)
[BOX64] Warning, CALL to 0x0 at 0x73173b (0x73173a)
[BOX64] Warning, CALL to 0x0 at 0x73215a (0x732159)
[BOX64] Warning, CALL to 0x0 at 0x732174 (0x732173)
[BOX64] Warning, CALL to 0x0 at 0x731aa5 (0x731aa4)
[BOX64] Warning, CALL to 0x0 at 0x731ad5 (0x731ad4)
[BOX64] Warning, CALL to 0x0 at 0x731b04 (0x731b03)
[BOX64] Warning, CALL to 0x0 at 0x731986 (0x731985)
[BOX64] Box64 arm64 v0.4.1 57e87b4ee with Dynarec built on Jan  9 2026 00:25:42
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 51 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/lib/icecream/libexec/icecc/bin/:/home/amir/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
[BOX64] Looking for /mnt/data/games/WarThunder/gaijin_selfupdater
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP
[BOX64] Running on Cortex-A520 with 12 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 1.0 GHz emulating 2.0 GHz
[BOX64] argv[1]="-appid"
[BOX64] argv[2]="WarThunderLauncherLinux"
[BOX64] argv[3]="-localversion"
[BOX64] argv[4]="1.0.3.38"
[BOX64] argv[5]="-execpath"
[BOX64] argv[6]="launcher"
[BOX64] argv[7]="-notify_user_about_failure"
[BOX64] Rename process to "gaijin_selfupdater"
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Warning, CALL to 0x0 at 0x7cecdb (0x7cecda)
[BOX64] Warning, CALL to 0x0 at 0x4f105c (0x4f105b)
[BOX64] Warning, CALL to 0x0 at 0x4f0027 (0x4f0026)
[BOX64] Warning, CALL to 0x0 at 0x4f004e (0x4f004d)
[BOX64] Warning, CALL to 0x0 at 0x4f0027 (0x4f0026)
[BOX64] Warning, CALL to 0x0 at 0x4f004e (0x4f004d)
[BOX64] Warning, CALL to 0x0 at 0x4f01ab (0x4f01aa)
[BOX64] Warning, CALL to 0x0 at 0x4f01dc (0x4f01db)
[BOX64] Warning, CALL to 0x0 at 0x4ef52b (0x4ef52a)
[BOX64] Warning, CALL to 0x0 at 0x4ef56a (0x4ef569)
[BOX64] Warning, CALL to 0x0 at 0x4ef5a6 (0x4ef5a5)
[BOX64] Warning, CALL to 0x0 at 0x4ef956 (0x4ef955)
[BOX64] Warning, CALL to 0x0 at 0x4ef70b (0x4ef70a)
[BOX64] Warning, CALL to 0x0 at 0x4f012a (0x4f0129)
[BOX64] Warning, CALL to 0x0 at 0x4f0144 (0x4f0143)
[BOX64] Warning, CALL to 0x0 at 0x4f012a (0x4f0129)
[BOX64] Warning, CALL to 0x0 at 0x4f0144 (0x4f0143)
[BOX64] Warning, CALL to 0x0 at 0x4efa75 (0x4efa74)
[BOX64] Warning, CALL to 0x0 at 0x4efaa5 (0x4efaa4)
[BOX64] Warning, CALL to 0x0 at 0x4efad4 (0x4efad3)
[BOX64] Warning, CALL to 0x0 at 0x4ef956 (0x4ef955)
[BOX64] Using emulated /mnt/data/games/WarThunder/libsciter-gtk.so
[BOX64] Warning, CALL to 0x0 at 0x71e775 (0x71e774)
[BOX64] Error: PltResolver: Symbol  gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 in /mnt/data/games/WarThunder/libsciter-gtk.so (local_maplib=0x5e662b50, global maplib=0x5e2fe1b0, deepbind=0)

(launcher:19754): Gtk-WARNING **: 02:31:19.404: drawing failure for widget 'GtkDrawingArea': cairo_restore() without matching cairo_save()

(launcher:19754): Gtk-WARNING **: 02:31:19.404: drawing failure for widget 'GtkWindow': cairo_restore() without matching cairo_save()
[BOX64] Error: PltResolver: Symbol  gtk_widget_add_tick_callback(ver 0: gtk_widget_add_tick_callback) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff029b7ea0 in /mnt/data/games/WarThunder/libsciter-gtk.so (local_maplib=0x5e662b50, global maplib=0x5e2fe1b0, deepbind=0)
[BOX64] Warning, CALL to 0x0 at 0x71e33f (0x71e33e)
[BOX64] Warning, CALL to 0x0 at 0x831c15 (0x831c14)
[BOX64] Warning, CALL to 0x0 at 0x831c15 (0x831c14)
[BOX64] Warning, CALL to 0x0 at 0x71e8be (0x71e8bd)
[BOX64] Warning, CALL to 0x0 at 0x71a0f1 (0x71a0f0)
[BOX64] Warning, CALL to 0x0 at 0x71c440 (0x71c43f)
[BOX64] Warning, CALL to 0x0 at 0x71a3b1 (0x71a3b0)
[BOX64] Sigfault/Segbus while quitting, exiting silently
```

However the game does seem to at least launch now? (Progress)
It gets stuck in the loading screen though... (Likely waiting for the anticheat to load or something)

<img width="1960" height="1120" alt="Image" src="https://github.com/user-attachments/assets/7e1e3a72-27ce-44c5-ba49-8744dfa43348" />

It's maxing out a single core though.
I've been waiting for around half an hour for this to load..
