### ISSUE TITLE
Failed to start wps-office 

### ISSUE THREAD

**Issue by lz-bro** [ptitSeb/box64#1703]
Hi,
Start wps with the latest box64, an exception occurred and the output is as follows

`
Dynarec for RISC-V With extension: I M A F D C Zba Zbb Zbc Zbs Vector (vlen: 256) PageSize:4096 Running on Unknown CPU with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 87 entries
Box64 with Dynarec v0.3.1 2e6acc86 built on Jul 22 2024 10:05:15
BOX64: Didn't detect 48bits of address space, considering it's 39bits
BOX64 will force the used of emulated libs for libqxcb.so 
Counted 41 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/wps
Rename process to "wps"
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libc++abi.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libtcmalloc_minimal.so.4
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/liblibsafec.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libc++.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libwpsmain.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libksolite.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkso.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libgriddrawer.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libwpsio.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkprometheus.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libsearchcore.so
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5XmlKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5NetworkKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5PrintSupportKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5X11ExtrasKso.so.5
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libthrift.so.0.13.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libxercesc3.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WidgetsKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5GuiKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5CoreKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicui18n.so.55
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicuuc.so.55
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicudata.so.55
Using native(wrapped) libgthread-2.0.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libstdc++.so.6
Using native(wrapped) libGL.so.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/krecentfile/libkrecentfile.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkdownload.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkcloudfiledialog.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5ConcurrentKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WebKitWidgets.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5DBusKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libcurl.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libcrypto.so.1.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libssl.so.1.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WebKit.so.5
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libxml2.so.2
Using native(wrapped) libxslt.so.1
Using native(wrapped) libsqlite3.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/konlinefileconfig/libkonlinefileconfig.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libqingipc.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libksqlite3.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/kmodule/libkmodule.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/kfpccomb/libkfpccomb.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/knetwork/libknetwork.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5SvgKso.so.5
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libmythes.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libIRLAS.so
QT_MESSAGE_PATTERN: Unknown placeholder %{if-cat
%{if-catLoader::%{if-catLoader() looking at "/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/qt/plugins/platforms/libqxcb.so"
"%{if-cato extrac%{if-cat meta data from '/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/qt/plugins/platforms/libqxcb.so'" 
%{if-cat not a plugin
%{if-catLoader::%{if-catLoader()%{if-catg directory path "/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/platforms" ...
%{if-catt find t%{if-catatform plugin "xcb" in ""
%{if-catlication%{if-catto start%{if-cat no Qt p%{if-catplugin c%{if-catinitiali%{if-catnstallin%{if-catplicatio%{if-catx this problem.

Dynarec for RISC-V With extension: I M A F D C Zba Zbb Zbc Zbs Vector (vlen: 256) PageSize:4096 Running on Unknown CPU with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 87 entries
Box64 with Dynarec v0.3.1 2e6acc86 built on Jul 22 2024 10:05:15
BOX64: Didn't detect 48bits of address space, considering it's 39bits
BOX64 will force the used of emulated libs for libqxcb.so 
Counted 42 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/transerr
argv[1]="-app=wps"
argv[2]="-ccrash=0"
argv[3]="-callfrom=1"
argv[4]="-cpid=3349"
argv[5]="-module=wps"
argv[6]="-dir="
Rename process to "transerr"
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libc++abi.so.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkso.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libksolite.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WidgetsKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5XmlKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5NetworkKso.so.5
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/liblibsafec.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5GuiKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5CoreKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libc++.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicui18n.so.55
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicuuc.so.55
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libicudata.so.55
Using native(wrapped) libgthread-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libstdc++.so.6
Using native(wrapped) libGL.so.1
root@k1:/home/bianbu/lz/box64# Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/konlinefileconfig/libkonlinefileconfig.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkdownload.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libqingipc.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libksqlite3.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/kmodule/libkmodule.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/kfpccomb/libkfpccomb.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/knetwork/libknetwork.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WebKitWidgets.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5SvgKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5X11ExtrasKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5DBusKso.so.5
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libthrift.so.0.13.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libcrypto.so.1.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libssl.so.1.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libcurl.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5WebKit.so.5
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libxml2.so.2
Using native(wrapped) libxslt.so.1
Using native(wrapped) libsqlite3.so.0
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5PrintSupportKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkcloudfiledialog.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libkprometheus.so
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libxercesc3.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libmythes.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libIRLAS.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/addons/krecentfile/libkrecentfile.so
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libQt5ConcurrentKso.so.5
Using emulated /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/libsearchcore.so
QT_MESSAGE_PATTERN: Unknown placeholder %{if-cat%1.kss.kLoader::%1.kss.kLoader()%1.kss.kg directory path "/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/qt/plugins/platforms" ...
%{if-catLoader::%{if-catLoader() looking at "/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/qt/plugins/platforms/libqxcb.so"
"%{if-cato extrac%{if-cat meta data from '/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/qt/plugins/platforms/libqxcb.so'" 
%{if-cat not a plugin
%{if-catLoader::%{if-catLoader()%{if-catg directory path "/root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/platforms" ...
%{if-catt find t%{if-catatform plugin "xcb" in ""
%{if-catlication%{if-catto start%{if-cat no Qt p%{if-catplugin c%{if-catinitiali%{if-catnstallin%{if-catplicatio%{if-catx this problem.

terminating with uncaught foreign exception
NativeBT: /root/.local/share/ruyi/binaries/x86_64/wps-office-11.1.0-r.11720/opt/kingsoft/wps-office/office6/transerr() [0x34a1c0ac]
NativeBT: linux-vdso.so.1(__vdso_rt_sigreturn+0) [0x3fbaba6800]
NativeBT: /lib/riscv64-linux-gnu/libc.so.6(+0x6c0da) [0x3fbaa920da]
NativeBT: /lib/riscv64-linux-gnu/libc.so.6(gsignal+0x12) [0x3fbaa5c29a]
NativeBT: /lib/riscv64-linux-gnu/libc.so.6(abort+0xac) [0x3fbaa4c3c4]
NativeBT: [0x3fb3d2da54]
EmulatedBT: box64(abort+0) [0x50080]
3360|SIGABRT @0x3fbaa920da (???(/lib/riscv64-linux-gnu/libc.so.6+0x6c0da)) (x64pc=0x50080/"???", rsp=0x3fba99c5b8, stack=0x3fba19e000:0x3fba99e000 own=(nil) fp=0x371912b0), for accessing 0xd20 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x000000003719d129 RSP-0x18:0x000000003719d0a8 RSP-0x10:0x00000000369d37d0 RSP-0x08:0x0000000000000004
RSP+0x00:0x0000003f000083b7 RSP+0x08:0x0000003fba99c758 RSP+0x10:0x0000003f0003ff18 RSP+0x18:0x000000000000365b
RAX:0x000000000000000a RCX:0x0000000000365be0 RDX:0x0000003fba99c670 RBX:0x0000003fbab7a4d8 
RSP:0x0000003fba99c5b8 RBP:0x00000000371912b0 RSI:0x0000003fbab7a318 RDI:0x000000000000000a 
 R8:0x0000000000000018  R9:0x00000000000000a1 R10:0x0000003f0003fee6 R11:0x0000000000000088 
R12:0x0000003f0c621540 R13:0x0000000000365bc0 R14:0x0000000000000000 R15:0x0000003fba99cc30 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 

`

**Comment by ptitSeb** [comment]
Can you bisect to find the offending commit?

**Comment by ksco** [comment]
Let me check.

**Comment by lz-bro** [comment]
> It works on my machine. So I guess this might be an issue specified to SpaceMiT K1 SoC, probably caused by the experimental RVV support.它适用于我的机器。所以我想这可能是 SpaceMiT K1 SoC 指定的问题，可能是由实验性 RVV 支持引起的。
> 
> ... I need to install a desktop OS on my K1 board to reproduce this, so it will take some time. Meanwhile, @lz-bro can you try `BOX64_DYNAREC_RV64NOEXT=1 box64 ./wps`? This will disable the usage of Zb* and Vector extensions....我需要在我的 K1 板上安装桌面操作系统才能重现它，所以这需要一些时间。同时，你能试试吗 `BOX64_DYNAREC_RV64NOEXT=1 box64 ./wps` ？这将禁用 Zb* 和 Vector 扩展。

It can start successfully. Thank you very much for your help :)

**Comment by lz-bro** [comment]
wps-office still has some program, I hope you can help take a look，thanks
1. wpp can start, but a segment error occurred when I clicking on 'New' 
2. et can't start
[et.log](https://github.com/user-attachments/files/16331265/et.log)
[wpp.log](https://github.com/user-attachments/files/16331267/wpp.log)

**Comment by ksco** [comment]
As the log suggested, you need to find the x86_64 version of libltdl.so.7, and put it into the office6/ directory.

**Comment by ksco** [comment]
@lz-bro can you retry on the latest main branch without the BOX64_DYANREC_RV64NOEXT=1 env variable?

**Comment by lz-bro** [comment]
> @lz-bro can you retry on the latest main branch without the BOX64_DYANREC_RV64NOEXT=1 env variable?

I retried，the BOX64_DYANREC_RV64NOEXT=1 env variable still need.

**Comment by ksco** [comment]
ack, thanks. I installed Armbian on my K1 and I can reproduce this, I'll have another look.

**Comment by ksco** [comment]
@lz-bro can you try again?

**Comment by ksco** [comment]
This should be random and has nothing to do with specific commit. In addition, I noticed that there are also some errors in some button text, but it’s not related to the RVV extension, which is strange and  requires further debugging.

**Comment by lz-bro** [comment]
Confirm it is random by git reset. There have also been some bugs, such as wps text is not displayed, I'm not sure if it's random.

**Comment by ksco** [comment]
The text misdiaplay are not random but it’s not related to RVV either, I need to debug that.

**Comment by lz-bro** [comment]
@ksco Hi, have you successfully run weixin?

**Comment by ksco** [comment]
> @ksco Hi, have you successfully run weixin?

Yes, you need a certain version of weixin as well as some hack to run it, but I can't tell you the details, sorry.

**Comment by lz-bro** [comment]
It's ok, can you tell me which version to use? thank you
http://archive.ubuntukylin.com/ubuntukylin/pool/partner/weixin_2.1.1_amd64.deb
https://github.com/lovechoudoufu/wechat_for_linux/releases/download/wechat-beta_1.0.0.238_amd64/wechat-beta_1.0.0.238_amd64_login.deb
or another

**Comment by ksco** [comment]
See: https://aur.archlinux.org/packages/wechat-uos-qt

**Comment by ksco** [comment]
Can you retry on the wps text display issue? This should be fixed now.

**Comment by lz-bro** [comment]
The text display is better than before, only one or two button text have display problems, and the random segmentation fault of wpp still exists.

**Comment by ksco** [comment]
Can you post some screenshots to show which button text still has issues?

**Comment by lz-bro** [comment]
![rv64ext_1](https://github.com/user-attachments/assets/dc6e09c9-67f6-40c1-9417-854c7df6a666)
![rv64noext_1](https://github.com/user-attachments/assets/3a5a7e9a-de26-4b56-85cc-0f794c750037)
![rv64ext_2](https://github.com/user-attachments/assets/6eb61c3b-2a55-4037-9797-56b243e53676)
![rv64noext_2](https://github.com/user-attachments/assets/df3d5ae1-8f6c-413c-a2e1-5a4fb99b0840)

**Comment by ksco** [comment]
I suppose the bottom ones are what it looks like on an x86_64 machine?

**Comment by ksco** [comment]
Never mind, I reproduced this on my BPI F3, the issue is still on the experimental RVV support, so I'll disable it for now, it's not ready for the enduser anyway.

**Comment by Botspot** [comment]
Why not use the ARM release of wps-office? For applications that have a native arm64 build, there should never be the need for emulation.

**Comment by ksco** [comment]
> Why not use the ARM release of wps-office? For applications that have a native arm64 build, there should never be the need for emulation.

Because we’re running on RISC-V machine here, hope they will release some RISC-V binary soon ;)

**Comment by ksco** [comment]
I've fixed several issues and re-enabled RVV by default in #1750 and #1755, now wps-office should be okay on K1.

**Comment by LukeShortCloud** [comment]
@lz-bro This should now be fixed. If you encounter any more issues, feel free to re-open this GitHub Issue. Closing as resolved.
