### ISSUE TITLE
xmlXPathNAN libexslt.so.0 functions

### ISSUE THREAD

**Issue by senioi** [ptitSeb/box64#209]
I try to run php7.4 on box64,
`Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.7 9bf7185 built on Jan 13 2022 10:55:45
BOX64_LD_LIBRARY_PATH: /home/ubuntu/boxlib/
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for /usr/local/php/bin/php
Using emulated libargon2.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) librt.so.1
Using emulated libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libxml2.so.2
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libz.so.1
Using native(wrapped) libcurl.so.4
Using emulated libjpeg.so.8
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libpng16.so.16
Using emulated libicuio.so.60
Using emulated libicui18n.so.60
Using emulated libicuuc.so.60
Using emulated libonig.so.4
Using emulated libsqlite3.so.0
Using emulated libsodium.so.23
Using native(wrapped) libxslt.so.1
Using emulated libexslt.so.0
Using emulated libzip.so.5
Using emulated libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using emulated libicudata.so.60
Using emulated libgcrypt.so.20
Using emulated libgpg-error.so.0
Error: Global Symbol xmlXPathNAN not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0df80 ((nil)) in libexslt.so.0
Error: Global Symbol xsltGenericErrorContext not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0df88 ((nil)) in libexslt.so.0
Error: Global Symbol xsltDocumentComp not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0df98 ((nil)) in libexslt.so.0
Error: Global Symbol xsltGenericDebugContext not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0dfa0 ((nil)) in libexslt.so.0
Error: Global Symbol xsltGenericDebug not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0dfb8 ((nil)) in libexslt.so.0
Error: Global Symbol xsltGenericError not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0dfd0 ((nil)) in libexslt.so.0
Error: Global Symbol xmlMallocAtomic not found, cannot apply R_X86_64_GLOB_DAT @0xffff96c0dfe8 ((nil)) in libexslt.so.0
Error: Global Symbol xmlTextReaderHasValue not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6c70 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstNamespaceUri not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6c78 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderIsDefault not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6c80 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndDTDElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6c90 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterWriteCDATA not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6ca0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderReadOuterXml not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6ca8 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndDocument not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6cb8 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xsltLibxmlVersion not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6ce0
((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterSetIndentString not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d10 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstName not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d18 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterStartPI not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d30 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderIsEmptyElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d50 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterWriteComment not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d60 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderHasAttributes not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d78 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstBaseUri not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d90 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xsltGenericError not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6d98 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderReadInnerXml not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6db8 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstXmlLang not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6dc0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterStartDTDElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6dc8 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterStartAttribute not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6dd0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderNodeType not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6df0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xsltLibxsltVersion not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e18 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderLookupNamespace not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e20 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstPrefix not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e38 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterStartElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e50 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderReadString not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e68 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderGetAttribute not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e88 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterWriteString not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6e98 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndDTD not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6eb0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterWriteRaw not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6ef0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterStartDTDAttlist not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6ef8 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstLocalName not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f08 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f10 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderConstValue not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f18 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndPI not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f20 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderAttributeCount not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f40 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndAttribute not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f48 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndComment not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f70 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndCDATA not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f78 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndDTDEntity not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f90 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterEndDTDAttlist not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6f98 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextWriterFullEndElement not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6fb0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xmlTextReaderDepth not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6fd0 ((nil)) in /usr/local/php/bin/php
Error: Global Symbol xsltGenericErrorContext not found, cannot apply R_X86_64_GLOB_DAT @0xffff9c9f6fd8 ((nil)) in /usr/local/php/bin/php
Warning, don't know of to handle rela #1631 type: R_X86_64_IRELATIVE on
Warning, don't know of to handle rela #1632 type: R_X86_64_IRELATIVE on
Warning, don't know of to handle rela #1633 type: R_X86_64_IRELATIVE on
Warning, don't know of to handle rela #1634 type: R_X86_64_IRELATIVE on
Using emulated /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/opcache.so
Using emulated /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/imagick.so
Using emulated libMagickWand-7.Q16HDRI.so.10
Using emulated libMagickCore-7.Q16HDRI.so.10
Using emulated libgomp.so.1
Using emulated /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/memcached.so
Using emulated libmemcached.so.11
Using emulated libsasl2.so.2
Error: PltResolver: Symbol __xmlParserVersion(ver 0: __xmlParserVersion) not found, cannot applyR_X86_64_JUMP_SLOT 0xffff9c9f6c38 (0xffff9bf3b216) in /usr/local/php/bin/php`

**Comment by rajdakin** [comment]
Is this fixed now? (Also, please use the block code feature instead of the quote feature to format large blocks of code:
\`\`\`
<text here>
\`\`\`
which is rendered as
```
<text here>
```
)

**Comment by LukeShortCloud** [comment]
This is probably still an issue. Some functions, such as `xmlXPathNAN`, are not wrapped.
