### ISSUE TITLE
Error loading needed lib libpcap.so.0.8

### ISSUE THREAD

**Issue by Ivan04012025** [ptitSeb/box64#2282]
Hi everyone,
I am trying to run lantern on my Raspberry Pi 3 with box64 installed from pre-built package. I get the following output:
lantern
Running installation script...
/usr/lib/lantern/lantern-binary: OK
Dynarec for ARM64, with extension: ASIMD CRC32
Running on Cortex-A53 with 4 cores, pagesize: 4096
Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 105 entries
Box64 with Dynarec v0.3.3 c98b4c8f built on Jan 21 2025 06:36:32
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 33 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /home/ivan/.lantern/bin/lantern
Rename process to "lantern"
Using native(wrapped) libresolv.so.2
Using native(wrapped) libayatana-appindicator3.so.1
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Error loading needed lib libpcap.so.0.8
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Error loading one of needed lib
Error: Loading needed libs in elf /home/ivan/.lantern/bin/lantern

It looks like it can not find libpcap.so.0.8, however when i try to install it by command
sudo apt install libpcap0.8 libpcap0.8-dev
i get:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpcap0.8 is already the newest version (1.10.3-1).
libpcap0.8-dev is already the newest version (1.10.3-1).
0 upgraded, 0 newly installed, 0 to remove and 75 not upgraded.

What is wrong here?

**Comment by Ivan04012025** [comment]
> that library `libcap.so.0.8` is not wrapped on box64, so you need the x86_64 version for now for it be used.

Thank you for a fast reply! this means all i need is just copy this lib file from my desktop x86_64 Ubuntu to RPi3 and it will work?

**Comment by ptitSeb** [comment]
> > that library `libcap.so.0.8` is not wrapped on box64, so you need the x86_64 version for now for it be used.
> 
> [@ptitSeb](https://github.com/ptitSeb), thank you for a fast reply! this means all i need is just copy this lib file from my desktop x86_64 Ubuntu to RPi3 and it will work?

Yeah, it will pickup the lib and continue from there....

**Comment by Ivan04012025** [comment]
Ok, now i get new issue:
lantern
Running installation script...
/usr/lib/lantern/lantern-binary: OK
Dynarec for ARM64, with extension: ASIMD CRC32
Running on Cortex-A53 with 4 cores, pagesize: 4096
Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 105 entries
Box64 with Dynarec v0.3.3 c98b4c8f built on Jan 21 2025 06:36:32
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 34 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /home/ivan/.lantern/bin/lantern
Rename process to "lantern"
Using native(wrapped) libresolv.so.2
Using native(wrapped) libayatana-appindicator3.so.1
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using emulated lib/libpcap.so.0.8
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libdbus-1.so.3
Error: Unsupported Syscall 0x89h (137)

@ptitSeb, is there a way to fix it?

**Comment by ptitSeb** [comment]
Well, I need to add that syscall to box64. It's `sys_statfs` so needs some specific wrapping of the stat struture I think. I'll add that to my todo.

**Comment by Ivan04012025** [comment]
Thank you!

**Comment by ptitSeb** [comment]
So, I decided to add wrapped libpcap instead. So it should works better now, unless it used one of the few symbols still not wrapped (it will complains about missing symbol in that case)

**Comment by Ivan04012025** [comment]
@ptitSeb, thanks. So what should i do to try it? Reinstall pre-built package will be enough? Or i have to build it from source ?

**Comment by ptitSeb** [comment]
> [@ptitSeb](https://github.com/ptitSeb), thanks. So what should i do to try it? Reinstall pre-built package will be enough? Or i have to build it from source ?

It's up to you. If you want to test right now, you need to build from source. Else, you'll have to wait for the pre-built package to be updated (tomorrow I guess?).

**Comment by Ivan04012025** [comment]
ok, i built it from source using git clone, this error still here with following output:
lantern
Running installation script...
/usr/lib/lantern/lantern-binary: OK
[BOX64] Dynarec for ARM64, with extension: ASIMD CRC32
[BOX64] Running on Cortex-A53 with 4 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Box64 with Dynarec v0.3.3 f0d87122 built on Jan 23 2025 16:03:15
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Counted 34 Env var
[BOX64] BOX64 LIB PATH: 
[BOX64] BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
[BOX64] Looking for /home/ivan/.lantern/bin/lantern
[BOX64] Rename process to "lantern"
[BOX64] Using native(wrapped) libresolv.so.2
[BOX64] Using native(wrapped) libayatana-appindicator3.so.1
[BOX64] Using native(wrapped) libgtk-3.so.0
[BOX64] Using native(wrapped) libgdk-3.so.0
[BOX64] Using native(wrapped) libgobject-2.0.so.0
[BOX64] Using native(wrapped) libglib-2.0.so.0
[BOX64] Using native(wrapped) libgio-2.0.so.0
[BOX64] Using native(wrapped) libgmodule-2.0.so.0
[BOX64] Using native(wrapped) libgdk_pixbuf-2.0.so.0
[BOX64] Using native(wrapped) libpangocairo-1.0.so.0
[BOX64] Using native(wrapped) libpango-1.0.so.0
[BOX64] Using native(wrapped) libcairo.so.2
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Error loading needed lib libpcap.so.0.8
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Error loading one of needed lib
[BOX64] Error: Loading needed libs in elf /home/ivan/.lantern/bin/lantern

i guess i have to wait for pre-built package update

**Comment by ptitSeb** [comment]
Ok, I pushed a small fix, can you update and try again?

**Comment by Ivan04012025** [comment]
Well, i built again, libpcap issue is gone, but still not working. Now output looks like this:

lantern
Running installation script...
/usr/lib/lantern/lantern-binary: OK
[BOX64] Dynarec for ARM64, with extension: ASIMD CRC32
[BOX64] Running on Cortex-A53 with 4 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Box64 with Dynarec v0.3.3 925f6a99 built on Jan 23 2025 20:03:09
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Counted 34 Env var
[BOX64] BOX64 LIB PATH: 
[BOX64] BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
[BOX64] Looking for /home/ivan/.lantern/bin/lantern
[BOX64] Rename process to "lantern"
[BOX64] Using native(wrapped) libresolv.so.2
[BOX64] Using native(wrapped) libayatana-appindicator3.so.1
[BOX64] Using native(wrapped) libgtk-3.so.0
[BOX64] Using native(wrapped) libgdk-3.so.0
[BOX64] Using native(wrapped) libgobject-2.0.so.0
[BOX64] Using native(wrapped) libglib-2.0.so.0
[BOX64] Using native(wrapped) libgio-2.0.so.0
[BOX64] Using native(wrapped) libgmodule-2.0.so.0
[BOX64] Using native(wrapped) libgdk_pixbuf-2.0.so.0
[BOX64] Using native(wrapped) libpangocairo-1.0.so.0
[BOX64] Using native(wrapped) libpango-1.0.so.0
[BOX64] Using native(wrapped) libcairo.so.2
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libpcap.so.0
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libbsd.so.0
runtime: g 1: unexpected return pc for runtime.sigpanic called from 0x31a
stack: frame={sp:0xa8165930, fp:0xa8165990} stack=[0xa8164000,0xa8166000)
0x00000000a8165830:  0x000000000044dba0 <runtime.(*_panic).nextFrame.func1+0x0000000000000000>  0x00000000a80061c0 
0x00000000a8165840:  0x00000000a81658a8  0x00000000a816582f 
0x00000000a8165850:  0x00000000a8165870  0x000000000044d8a5 <runtime.(*_panic).start+0x0000000000000145> 
0x00000000a8165860:  0x00000000a80061c0  0x00000000a80061c0 
0x00000000a8165870:  0x00000000a8165920  0x000000000044d528 <runtime.gopanic+0x0000000000000128> 
0x00000000a8165880:  0x0000000000000000  0x0000000000000000 
0x00000000a8165890:  0x732f707865676572  0x61722e7861746e79 
0x00000000a81658a0:  0x00000000016140e0  0x0000000000000000 
0x00000000a81658b0:  0x00000000016140e0  0x0000000002c00b10 
0x00000000a81658c0:  0x0000000000000000  0x000000000044d528 <runtime.gopanic+0x0000000000000128> 
0x00000000a81658d0:  0x00000000a8165880  0x0000000000000000 
0x00000000a81658e0:  0x0000000000466e78 <runtime.sigpanic+0x0000000000000378>  0x00000000a8165930 
0x00000000a81658f0:  0x0000000000000000  0x0000000000000000 
0x00000000a8165900:  0x0000000000000000  0x0000000000000000 
0x00000000a8165910:  0x000007c9000007c0  0x0000000002c00b10 
0x00000000a8165920:  0x00000000a8165980  0x0000000000466e78 <runtime.sigpanic+0x0000000000000378> 
0x00000000a8165930: <0x00000000016140e0  0x0000000002c00b10 
0x00000000a8165940:  0x0000058800000560  0x000005ea000005d0 
0x00000000a8165950:  0x000005f2000005ef  0x0000064a00000620 
0x00000000a8165960:  0x00000000a80061c0  0x0000000000000000 
0x00000000a8165970:  0x0000000000000206  0x00000000a81659b0 
0x00000000a8165980:  0x00000000a81659b0  0x000000000000031a 
0x00000000a8165990: >0x0000000000000009  0x0000000000000004 
0x00000000a81659a0:  0x00000000000002ed  0x000000000000018f 
0x00000000a81659b0:  0x00000000a8165a48  0x00000000004be8ab <sort.pdqsort+0x000000000000022b> 
0x00000000a81659c0:  0x000000000208d8e0  0x00000000a8394568 
0x00000000a81659d0:  0x0000000000000000  0x000000000000031d 
0x00000000a81659e0:  0x00000b6f00000b66  0x010130070001034a 
0x00000000a81659f0:  0x000000090001034a  0x0000030a00003007 
0x00000000a8165a00:  0x0000000000000001  0x000000000000031d 
0x00000000a8165a10:  0x00000000a8165aa0  0x00000000007647aa <regexp/syntax.(*parser).parseUnicodeClass+0x00000000000003aa> 
0x00000000a8165a20:  0x000000000000018e  0x000000000000000a 
0x00000000a8165a30:  0x00000000018cb579  0x000000000000031d 
0x00000000a8165a40:  0x0000000000000000  0x00000000a8165a80 
0x00000000a8165a50:  0x00000000004bc8d4 <sort.Sort+0x0000000000000054>  0x000000000208d8e0 
0x00000000a8165a60:  0x00000000a8394568  0x0000000000000005 
0x00000000a8165a70:  0x0000000000000001  0x000000000000001e 
0x00000000a8165a80:  0x00000000a8165aa0  0x0000000000765146 <regexp/syntax.cleanClass+0x0000000000000026> 
fatal error: unknown caller pc

runtime stack:
runtime.throw({0x187bdb5?, 0x28665d0?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:1023 +0x5c fp=0x7fa8d8b1a8 sp=0x7fa8d8b178 pc=0x44e01c
runtime.(*unwinder).next(0x7fa8d8b250)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/traceback.go:469 +0x24c fp=0x7fa8d8b220 sp=0x7fa8d8b1a8 pc=0x4799ac
runtime.(*_panic).nextFrame.func1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:938 +0xa6 fp=0x7fa8d8b2d8 sp=0x7fa8d8b220 pc=0x44dc46
runtime.systemstack(0x48c09f)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:509 +0x4a fp=0x7fa8d8b2e8 sp=0x7fa8d8b2d8 pc=0x48766a

goroutine 1 gp=0xa80061c0 m=0 mp=0x2e25560 [running, locked to thread]:
runtime.systemstack_switch()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:474 +0x8 fp=0xa8165820 sp=0xa8165810 pc=0x487608
runtime.(*_panic).nextFrame(0xa80061c0?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:911 +0x65 fp=0xa8165860 sp=0xa8165820 pc=0x44db65
runtime.(*_panic).start(0x0?, 0x0?, 0x732f707865676572?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:824 +0x145 fp=0xa8165880 sp=0xa8165860 pc=0x44d8a5
panic({0x16140e0?, 0x2c00b10?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:764 +0x128 fp=0xa8165930 sp=0xa8165880 pc=0x44d528
runtime.panicmem(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:261
runtime.sigpanic()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/signal_unix.go:881 +0x378 fp=0xa8165990 sp=0xa8165930 pc=0x466e78
runtime: g 1: unexpected return pc for runtime.sigpanic called from 0x31a
stack: frame={sp:0xa8165930, fp:0xa8165990} stack=[0xa8164000,0xa8166000)
0x00000000a8165830:  0x000000000044dba0 <runtime.(*_panic).nextFrame.func1+0x0000000000000000>  0x00000000a80061c0 
0x00000000a8165840:  0x00000000a81658a8  0x00000000a816582f 
0x00000000a8165850:  0x00000000a8165870  0x000000000044d8a5 <runtime.(*_panic).start+0x0000000000000145> 
0x00000000a8165860:  0x00000000a80061c0  0x00000000a80061c0 
0x00000000a8165870:  0x00000000a8165920  0x000000000044d528 <runtime.gopanic+0x0000000000000128> 
0x00000000a8165880:  0x0000000000000000  0x0000000000000000 
0x00000000a8165890:  0x732f707865676572  0x61722e7861746e79 
0x00000000a81658a0:  0x00000000016140e0  0x0000000000000000 
0x00000000a81658b0:  0x00000000016140e0  0x0000000002c00b10 
0x00000000a81658c0:  0x0000000000000000  0x000000000044d528 <runtime.gopanic+0x0000000000000128> 
0x00000000a81658d0:  0x00000000a8165880  0x0000000000000000 
0x00000000a81658e0:  0x0000000000466e78 <runtime.sigpanic+0x0000000000000378>  0x00000000a8165930 
0x00000000a81658f0:  0x0000000000000000  0x0000000000000000 
0x00000000a8165900:  0x0000000000000000  0x0000000000000000 
0x00000000a8165910:  0x000007c9000007c0  0x0000000002c00b10 
0x00000000a8165920:  0x00000000a8165980  0x0000000000466e78 <runtime.sigpanic+0x0000000000000378> 
0x00000000a8165930: <0x00000000016140e0  0x0000000002c00b10 
0x00000000a8165940:  0x0000058800000560  0x000005ea000005d0 
0x00000000a8165950:  0x000005f2000005ef  0x0000064a00000620 
0x00000000a8165960:  0x00000000a80061c0  0x0000000000000000 
0x00000000a8165970:  0x0000000000000206  0x00000000a81659b0 
0x00000000a8165980:  0x00000000a81659b0  0x000000000000031a 
0x00000000a8165990: >0x0000000000000009  0x0000000000000004 
0x00000000a81659a0:  0x00000000000002ed  0x000000000000018f 
0x00000000a81659b0:  0x00000000a8165a48  0x00000000004be8ab <sort.pdqsort+0x000000000000022b> 
0x00000000a81659c0:  0x000000000208d8e0  0x00000000a8394568 
0x00000000a81659d0:  0x0000000000000000  0x000000000000031d 
0x00000000a81659e0:  0x00000b6f00000b66  0x010130070001034a 
0x00000000a81659f0:  0x000000090001034a  0x0000030a00003007 
0x00000000a8165a00:  0x0000000000000001  0x000000000000031d 
0x00000000a8165a10:  0x00000000a8165aa0  0x00000000007647aa <regexp/syntax.(*parser).parseUnicodeClass+0x00000000000003aa> 
0x00000000a8165a20:  0x000000000000018e  0x000000000000000a 
0x00000000a8165a30:  0x00000000018cb579  0x000000000000031d 
0x00000000a8165a40:  0x0000000000000000  0x00000000a8165a80 
0x00000000a8165a50:  0x00000000004bc8d4 <sort.Sort+0x0000000000000054>  0x000000000208d8e0 
0x00000000a8165a60:  0x00000000a8394568  0x0000000000000005 
0x00000000a8165a70:  0x0000000000000001  0x000000000000001e 
0x00000000a8165a80:  0x00000000a8165aa0  0x0000000000765146 <regexp/syntax.cleanClass+0x0000000000000026> 

goroutine 18 gp=0xa809a380 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:402 +0xce fp=0xa806a7a8 sp=0xa806a788 pc=0x450fce
runtime.goparkunlock(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:408
runtime.forcegchelper()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:326 +0xb3 fp=0xa806a7e0 sp=0xa806a7a8 pc=0x450e33
runtime.goexit({})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xa806a7e8 sp=0xa806a7e0 pc=0x489621
created by runtime.init.6 in goroutine 1
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:314 +0x1a

goroutine 19 gp=0xa809a540 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:402 +0xce fp=0xa806af80 sp=0xa806af60 pc=0x450fce
runtime.goparkunlock(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:408
runtime.bgsweep(0xa80a8000)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgcsweep.go:278 +0x94 fp=0xa806afc8 sp=0xa806af80 pc=0x43a674
runtime.gcenable.gowrap1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgc.go:203 +0x25 fp=0xa806afe0 sp=0xa806afc8 pc=0x42efa5
runtime.goexit({})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xa806afe8 sp=0xa806afe0 pc=0x489621
created by runtime.gcenable in goroutine 1
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgc.go:203 +0x66

goroutine 20 gp=0xa809a700 m=nil [GC scavenge wait]:
runtime.gopark(0xa80a8000?, 0x20731c8?, 0x1?, 0x0?, 0xa809a700?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:402 +0xce fp=0xa806b778 sp=0xa806b758 pc=0x450fce
runtime.goparkunlock(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x2e23980)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xa806b7a8 sp=0xa806b778 pc=0x438049
runtime.bgscavenge(0xa80a8000)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgcscavenge.go:653 +0x3c fp=0xa806b7c8 sp=0xa806b7a8 pc=0x4385dc
runtime.gcenable.gowrap2()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgc.go:204 +0x25 fp=0xa806b7e0 sp=0xa806b7c8 pc=0x42ef45
runtime.goexit({})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xa806b7e8 sp=0xa806b7e0 pc=0x489621
created by runtime.gcenable in goroutine 1
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mgc.go:204 +0xa5

goroutine 2 gp=0xa8007340 m=nil [finalizer wait]:
runtime.gopark(0xa806e648?, 0x422145?, 0xa8?, 0x1?, 0x1849b60?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/proc.go:402 +0xce fp=0xa806e620 sp=0xa806e600 pc=0x450fce
runtime.runfinq()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mfinal.go:194 +0x107 fp=0xa806e7e0 sp=0xa806e620 pc=0x42dfe7
runtime.goexit({})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xa806e7e8 sp=0xa806e7e0 pc=0x489621
created by runtime.createfing in goroutine 1
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/mfinal.go:164 +0x3d

It seems like fixing  it will be a long shot...

**Comment by Ivan04012025** [comment]
@ptitSeb, it's ok. Thank you for trying. I will look for another vpn that works on raspberry pi
