### ISSUE TITLE
Turtle wow keeps disconnected after login

### ISSUE THREAD

**Issue by FrontMage** [ptitSeb/box64#2739]
Using winlator Winlator 10.0 (Hotfix) Mar 1 build with box64 0.3.2

Turtle wow can be found `https://turtle-wow.org/`

Box64 log as follow
```bash
Box64 with Dynarec v0.3.2  built on Feb 17 2025 15:44:18
Debug level is 1
Dynarec is on
Dynarec will continue block for 128 bytes on forward jump
Dynarec will not use weakbarrier on strong memory emulation
Dynarec will use only double for x87 emulation
Dynarec will try to generate x86 precise IEEE->int rounding
Dynarec will play it safe with x64 flags
Dynarec will not optimize CALL/RET
Dynarec will not use native flags if possible
Dynarec will print missing opcodes
BOX64 will not detect UnityPlayer.dll
Hack to force libX11 GLX extension present
Show Segfault signal even if a signal handler is present
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:4096 Running on Unknown CPU with 8 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Box64 with Dynarec v0.3.2  built on Feb 17 2025 15:44:18
BOX64: Wine preloader detected, loading "/data/user/0/com.winlator/files/rootfs/opt/wine/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-000d26000"
BOX64: Didn't detect 48bits of address space, considering it's 39bits
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
BOX64: Detected running wine with "WoW.exe"
Counted 57 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/data/user/0/com.winlator/files/rootfs/opt/wine/bin/:/data/user/0/com.winlator/files/rootfs/usr/local/bin/:/data/user/0/com.winlator/files/rootfs/usr/bin/
Looking for /data/user/0/com.winlator/files/rootfs/opt/wine/bin/wine
argv[1]="D:\twmoa_1172\WoW.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
14385|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so"/0x4a9fa490, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /data/user/0/com.winlator/files/rootfs/lib/x86_64-linux-gnu/libgcc_s.so.1
dlopen: New handle 0x4 (/data/user/0/com.winlator/files/rootfs/opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so), dlopened=1
14385|Call to dlsym(0x4, "__wine_main")0x3f00030bf0
14385|Call to dlsym((nil), "wine_main_preload_info")0x100004050
14385|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/win32u.so"/0x4aa12560, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
dlopen: New handle 0x5 (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/win32u.so), dlopened=1
14385|Call to dlsym(0x5, "__wine_unix_call_funcs")0x3f02141528
14385|Call to dlopen("libfreetype.so.6"/0x3f02103bcd, 2)
Using native(wrapped) libfreetype.so.6
dlopen: New handle 0x6 (libfreetype.so.6), dlopened=1
...
Calling my_vkGetInstanceProcAddr(0x4ab4f610, "vkCreateXlibSurfaceKHR") => 0x30110160 (cached)
14385|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/winealsa.so"/0x4ab84750, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/winealsa.so
Using native(wrapped) libasound.so.2
dlopen: New handle 0x18 (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/winealsa.so), dlopened=1
14385|Call to dlsym(0x18, "__wine_unix_call_wow64_funcs")0x3f0a013b80
14385|Call to dlsym(0x18, "__wine_unix_call_wow64_funcs")0x3f0a013b80
0x797eb329: Dynarec stopped because of x86 Opcode EA 04 34 11 36 BC 3F 66 66 66 66 66 66 21 40
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/secur32.so"/0x75f400a760, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/secur32.so
dlopen: New handle 0x19 (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/secur32.so), dlopened=1
14558|Call to dlsym(0x19, "__wine_unix_call_wow64_funcs")0x3f0b009b60
14558|Call to dlopen("libgnutls.so.30"/0x3f0b006252, 2)
Using native(wrapped) libgnutls.so.30
dlopen: New handle 0x1a (libgnutls.so.30), dlopened=1
14558|Call to dlsym(0x1a, "gnutls_alert_get")0x302c0000
14558|Call to dlsym(0x1a, "gnutls_alert_get_name")0x302c0020
14558|Call to dlsym(0x1a, "gnutls_alert_send")0x302c0040
14558|Call to dlsym(0x1a, "gnutls_certificate_allocate_credentials")0x302c0060
14558|Call to dlsym(0x1a, "gnutls_certificate_free_credentials")0x302c0080
14558|Call to dlsym(0x1a, "gnutls_certificate_get_peers")0x302c00a0
14558|Call to dlsym(0x1a, "gnutls_certificate_set_x509_key")0x302c00c0
14558|Call to dlsym(0x1a, "gnutls_cipher_get")0x302c00e0
14558|Call to dlsym(0x1a, "gnutls_cipher_get_key_size")0x302c0100
14558|Call to dlsym(0x1a, "gnutls_credentials_set")0x302c0120
14558|Call to dlsym(0x1a, "gnutls_deinit")0x302c0140
14558|Call to dlsym(0x1a, "gnutls_global_deinit")0x302c0160
14558|Call to dlsym(0x1a, "gnutls_global_init")0x302c0180
14558|Call to dlsym(0x1a, "gnutls_global_set_log_function")0x302c01a0
14558|Call to dlsym(0x1a, "gnutls_global_set_log_level")0x302c01c0
14558|Call to dlsym(0x1a, "gnutls_handshake")0x302c01e0
14558|Call to dlsym(0x1a, "gnutls_init")0x302c0200
14558|Call to dlsym(0x1a, "gnutls_kx_get")0x302c0220
14558|Call to dlsym(0x1a, "gnutls_mac_get")0x302c0240
14558|Call to dlsym(0x1a, "gnutls_mac_get_key_size")0x302c0260
14558|Call to dlsym(0x1a, "gnutls_perror")0x302c0280
14558|Call to dlsym(0x1a, "gnutls_protocol_get_version")0x302c02a0
14558|Call to dlsym(0x1a, "gnutls_priority_set_direct")0x302c02c0
14558|Call to dlsym(0x1a, "gnutls_privkey_deinit")0x302c02e0
14558|Call to dlsym(0x1a, "gnutls_privkey_init")0x302c0300
14558|Call to dlsym(0x1a, "gnutls_record_get_max_size")0x302c0320
14558|Call to dlsym(0x1a, "gnutls_record_recv")0x302c0340
14558|Call to dlsym(0x1a, "gnutls_record_send")0x302c0360
14558|Call to dlsym(0x1a, "gnutls_server_name_set")0x302c0380
14558|Call to dlsym(0x1a, "gnutls_session_channel_binding")0x302c03a0
14558|Call to dlsym(0x1a, "gnutls_set_default_priority")0x302c03c0
14558|Call to dlsym(0x1a, "gnutls_transport_get_ptr")0x302c03e0
14558|Call to dlsym(0x1a, "gnutls_transport_set_errno")0x302c0400
14558|Call to dlsym(0x1a, "gnutls_transport_set_ptr")0x302c0420
14558|Call to dlsym(0x1a, "gnutls_transport_set_pull_function")0x302c0440
14558|Call to dlsym(0x1a, "gnutls_transport_set_push_function")0x302c0460
14558|Call to dlsym(0x1a, "gnutls_x509_crt_deinit")0x302c0480
14558|Call to dlsym(0x1a, "gnutls_x509_crt_import")0x302c04a0
14558|Call to dlsym(0x1a, "gnutls_x509_crt_init")0x302c04c0
14558|Call to dlsym(0x1a, "gnutls_x509_privkey_deinit")0x302c04e0
14558|Call to dlsym(0x1a, "gnutls_cipher_get_block_size")0x302c0500
14558|Call to dlsym(0x1a, "gnutls_transport_set_pull_timeout_function")0x302c0520
14558|Call to dlsym(0x1a, "gnutls_alpn_set_protocols")0x302c0540
14558|Call to dlsym(0x1a, "gnutls_alpn_get_selected_protocol")0x302c0560
14558|Call to dlsym(0x1a, "gnutls_dtls_set_mtu")0x302c0580
14558|Call to dlsym(0x1a, "gnutls_dtls_set_timeouts")0x302c05a0
14558|Call to dlsym(0x1a, "gnutls_privkey_export_x509")0x302c05c0
14558|Call to dlsym(0x1a, "gnutls_privkey_import_rsa_raw")0x302c05e0
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/kerberos.so"/0x75f402c0d0, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/kerberos.so
dlopen: New handle 0x1b (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/kerberos.so), dlopened=1
14558|Call to dlsym(0x1b, "__wine_unix_call_wow64_funcs")0x3f0c007d00
14558|Call to dlopen("libkrb5.so.3"/0x3f0c005000, 2)
Error initializing native libkrb5.so.3 (last dlerror is libkrb5.so.3: cannot open shared object file: No such file or directory)
Error loading needed lib libkrb5.so.3
Warning: Cannot dlopen("libkrb5.so.3"/0x3f0c005000, 2)
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/netapi32.so"/0x75f402f3d0, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/netapi32.so
dlopen: New handle 0x1c (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/netapi32.so), dlopened=1
14558|Call to dlsym(0x1c, "__wine_unix_call_wow64_funcs")(nil)
Call to dlsym(netapi32.so, "__wine_unix_call_wow64_funcs") Symbol not found
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/msv1_0.so"/0x75f402f7b0, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/msv1_0.so
dlopen: New handle 0x1d (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/msv1_0.so), dlopened=1
14558|Call to dlsym(0x1d, "__wine_unix_call_wow64_funcs")0x3f0e003d80
posix_spawnp(0x105b0f784, "ntlm_auth", 0x105b0f560, (nil), 0x105b0f5e0, 0x76c689e430), IsX86=0 / fullpath="ntlm_auth"
Call to dlclose(0x1d)
Call to dlclose(0x1c)
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/bcrypt.so"/0x75f403c9b0, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/bcrypt.so
dlopen: New handle 0x1e (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/bcrypt.so), dlopened=1
14558|Call to dlsym(0x1e, "__wine_unix_call_wow64_funcs")0x3f0f00aca0
14558|Call to dlopen("libgnutls.so.30"/0x3f0f0080e2, 2)
dlopen: Recycling libgnutls.so.30/0x1a count=2 (dlopened=1, elf_index=-1)
14558|Call to dlsym(0x1a, "gnutls_cipher_decrypt2")0x302c0600
14558|Call to dlsym(0x1a, "gnutls_cipher_deinit")0x302c0620
14558|Call to dlsym(0x1a, "gnutls_cipher_encrypt2")0x302c0640
14558|Call to dlsym(0x1a, "gnutls_cipher_init")0x302c0660
14558|Call to dlsym(0x1a, "gnutls_dh_params_deinit")0x302c0680
14558|Call to dlsym(0x1a, "gnutls_dh_params_export_raw")0x302c06a0
14558|Call to dlsym(0x1a, "gnutls_dh_params_import_raw")0x302c06c0
14558|Call to dlsym(0x1a, "gnutls_dh_params_init")0x302c06e0
14558|Call to dlsym(0x1a, "gnutls_global_deinit")0x302c0160
14558|Call to dlsym(0x1a, "gnutls_global_init")0x302c0180
14558|Call to dlsym(0x1a, "gnutls_global_set_log_function")0x302c01a0
14558|Call to dlsym(0x1a, "gnutls_global_set_log_level")0x302c01c0
14558|Call to dlsym(0x1a, "gnutls_perror")0x302c0280
14558|Call to dlsym(0x1a, "gnutls_privkey_deinit")0x302c02e0
14558|Call to dlsym(0x1a, "gnutls_privkey_import_dsa_raw")0x302c0700
14558|Call to dlsym(0x1a, "gnutls_privkey_init")0x302c0300
14558|Call to dlsym(0x1a, "gnutls_privkey_sign_hash")0x302c0720
14558|Call to dlsym(0x1a, "gnutls_pubkey_deinit")0x302c0740
14558|Call to dlsym(0x1a, "gnutls_pubkey_import_privkey")0x302c0760
14558|Call to dlsym(0x1a, "gnutls_pubkey_init")0x302c0780
14558|Call to dlsym(0x1a, "gnutls_cipher_tag")0x302c07a0
14558|Call to dlsym(0x1a, "gnutls_cipher_add_auth")0x302c07c0
14558|Call to dlsym(0x1a, "gnutls_decode_rs_value")0x302c07e0
14558|Call to dlsym(0x1a, "gnutls_pk_to_sign")0x302c0800
14558|Call to dlsym(0x1a, "gnutls_privkey_decrypt_data")0x302c0820
14558|Call to dlsym(0x1a, "gnutls_privkey_derive_secret")0x302c0840
14558|Call to dlsym(0x1a, "gnutls_privkey_export_dh_raw")0x302c0860
14558|Call to dlsym(0x1a, "gnutls_privkey_export_dsa_raw")0x302c0880
14558|Call to dlsym(0x1a, "gnutls_privkey_export_ecc_raw")0x302c08a0
14558|Call to dlsym(0x1a, "gnutls_privkey_export_rsa_raw")0x302c08c0
14558|Call to dlsym(0x1a, "gnutls_privkey_generate2")0x302c08e0
14558|Call to dlsym(0x1a, "gnutls_privkey_import_dh_raw")0x302c0900
14558|Call to dlsym(0x1a, "gnutls_privkey_import_ecc_raw")0x302c0920
14558|Call to dlsym(0x1a, "gnutls_privkey_import_rsa_raw")0x302c05e0
14558|Call to dlsym(0x1a, "gnutls_privkey_set_spki")0x302c0940
14558|Call to dlsym(0x1a, "gnutls_pubkey_encrypt_data")0x302c0960
14558|Call to dlsym(0x1a, "gnutls_pubkey_export_dh_raw")0x302c0980
14558|Call to dlsym(0x1a, "gnutls_pubkey_export_dsa_raw")0x302c09a0
14558|Call to dlsym(0x1a, "gnutls_pubkey_export_ecc_raw")0x302c09c0
14558|Call to dlsym(0x1a, "gnutls_pubkey_export_rsa_raw")0x302c09e0
14558|Call to dlsym(0x1a, "gnutls_pubkey_import_dh_raw")0x302c0a00
14558|Call to dlsym(0x1a, "gnutls_pubkey_import_dsa_raw")0x302c0a20
14558|Call to dlsym(0x1a, "gnutls_pubkey_import_ecc_raw")0x302c0a40
14558|Call to dlsym(0x1a, "gnutls_pubkey_import_rsa_raw")0x302c0a60
14558|Call to dlsym(0x1a, "gnutls_pubkey_set_spki")0x302c0a80
14558|Call to dlsym(0x1a, "gnutls_pubkey_verify_hash2")0x302c0aa0
14558|Call to dlsym(0x1a, "gnutls_x509_spki_deinit")0x302c0ac0
14558|Call to dlsym(0x1a, "gnutls_x509_spki_init")0x302c0ae0
14558|Call to dlsym(0x1a, "gnutls_x509_spki_set_rsa_pss_params")0x302c0b00
14558|Call to dlopen("/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/crypt32.so"/0x75f40335d0, 2)
Using emulated /data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/crypt32.so
dlopen: New handle 0x1f (/data/user/0/com.winlator/files/rootfs/opt/wine/lib/wine/x86_64-unix/crypt32.so), dlopened=1
14558|Call to dlsym(0x1f, "__wine_unix_call_wow64_funcs")0x3f10005d00
14558|Call to dlopen("libgnutls.so.30"/0x3f1000403b, 2)
dlopen: Recycling libgnutls.so.30/0x1a count=3 (dlopened=1, elf_index=-1)
14558|Call to dlsym(0x1a, "gnutls_global_deinit")0x302c0160
14558|Call to dlsym(0x1a, "gnutls_global_init")0x302c0180
14558|Call to dlsym(0x1a, "gnutls_global_set_log_function")0x302c01a0
14558|Call to dlsym(0x1a, "gnutls_global_set_log_level")0x302c01c0
14558|Call to dlsym(0x1a, "gnutls_perror")0x302c0280
14558|Call to dlsym(0x1a, "gnutls_pkcs12_deinit")0x302c0b20
14558|Call to dlsym(0x1a, "gnutls_pkcs12_import")0x302c0b40
14558|Call to dlsym(0x1a, "gnutls_pkcs12_init")0x302c0b60
14558|Call to dlsym(0x1a, "gnutls_pkcs12_simple_parse")0x302c0b80
14558|Call to dlsym(0x1a, "gnutls_x509_crt_export")0x302c0ba0
14558|Call to dlsym(0x1a, "gnutls_x509_privkey_export_rsa_raw2")0x302c0bc0
14558|Call to dlsym(0x1a, "gnutls_x509_privkey_get_pk_algorithm2")0x302c0be0
0xe5d41a3: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 FC 8B 45 F0 8B 4D FC FF
0xe5d41a3: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 FC 8B 45 F0 8B 4D FC FF
0xe5d4308: Dynarec stopped because of x86 Opcode 63 D0 87 45 F4 87 55 FC 8B 5D F0 FF 75 F8 8B
0xe5d4308: Dynarec stopped because of x86 Opcode 63 D0 87 45 F4 87 55 FC 8B 5D F0 FF 75 F8 8B
0xe5d43b7: Dynarec stopped because of x86 Opcode 63 D0 87 45 F0 87 55 F8 8B 4D F4 8B 55 F8 8B
0xe5d43b7: Dynarec stopped because of x86 Opcode 63 D0 87 45 F0 87 55 F8 8B 4D F4 8B 55 F8 8B
0xe5d46a9: Dynarec stopped because of x86 Opcode 63 D0 87 45 FC 87 55 F8 8B 55 F4 8B 7D F8 8B
0xe5d46a9: Dynarec stopped because of x86 Opcode 63 D0 87 45 FC 87 55 F8 8B 55 F4 8B 7D F8 8B
0xe5d49af: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 FC 8B 55 F0 8B 45 FC 8B
0xe5d49af: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 FC 8B 55 F0 8B 45 FC 8B
0xe5d4b32: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 F4 8B 4D F8 8B 45 FC 8B
0xe5d4b32: Dynarec stopped because of x86 Opcode 63 D0 87 45 F8 87 55 F4 8B 4D F8 8B 45 FC 8B
Call to dlclose(0x4)
Call to dlclose(0x5)
Call to dlclose(0x6)
Call to dlclose(0x7)
Call to dlclose(0x8)
Call to dlclose(0x9)
Call to dlclose(0xa)
Call to dlclose(0xb)
Call to dlclose(0xc)
Call to dlclose(0xc)
Call to dlclose(0xd)
Call to dlclose(0xf)
Call to dlclose(0x10)
Call to dlclose(0x11)
Call to dlclose(0x12)
Call to dlclose(0x13)
Call to dlclose(0x15)
Call to dlclose(0x17)
Call to dlclose(0x18)
Call to dlclose(0x19)
Call to dlclose(0x1a)
Call to dlclose(0x1a)
Call to dlclose(0x1a)
Call to dlclose(0x1b)
Call to dlclose(0x1e)
Emit Signal 11 at IP=0x3f0a005acd(??? / ?) / addr=0x3f0a005acd, code=0xecec
Call to dlclose(0x1f)
ES=0x002b CS=0x0033 SS=0x002b DS=0x002b FS=0x0043 GS=0x0053
RAX=00000000000001e0 RCX=0000000000000000 RDX=00000076c6c40b68 RBX=000000000aad0000 RSP=000000010190fa90 FLAGS=----A--
RBP=00000000000001e0 RSI=0000000000000001 RDI=00000076c6ad8e04  R8=0000000000000000  R9=000000004ae22b60 
R10=000000004ae24640 R11=0000000000000000 R12=0000000000000000 R13=00000000000005a0 R14=000000004ae23840 
R15=00000000000001e0 RIP=0000003f0a005acd Emu Stack: 0x101810000 0x100000
Signal 11: si_addr=0x3f0a005acd, TRAPNO=14, ERR=21, RIP=0x3f0a005acd, prot=0, mmapped:0
Context has been changed in Sigactionhanlder, doing siglongjmp to resume emu at 0x3f0004340f, RSP=0x10190fa90
Sigfault/Segbus while quitting, exiting silently
```
I think it is the `Call to dlsym(netapi32.so, "__wine_unix_call_wow64_funcs") Symbol not found` causing the disconnect issue. full log can be found at clips

[box64-14385-1.txt](https://github.com/user-attachments/files/20719490/box64-14385-1.txt)

**Comment by ksco** [comment]
v0.3.2 is a (very) old version, please try again with the latest head of v0.3.7, it might have been fixed.

**Comment by FrontMage** [comment]
@ksco Switching to 0.3.6 still gets the same issue, running with winlator amod at `https://github.com/afeimod/winlator-mod/releases/tag/10.0Hotfix-Amod1` using its contents tab to install box 0.3.6
I cant seemed to find 0.3.7 release notes, is it an alpha build?

**Comment by ksco** [comment]
The last digit of the version number. Even numbers are official versions, and odd numbers are rolling development versions. You can download the latest head from: https://github.com/ptitSeb/box64/actions/runs/15611335299 (the Artifacts section)

**Comment by FrontMage** [comment]
@ksco the latest 0.3.7 build wont even start it just crashed on winlator

**Comment by FrontMage** [comment]
@ksco The linking makes it only works if it is built into the winlator imagefs
```bash
file box64
box64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter 
/data/data/com.winlator/files/imagefs/usr/lib/ld-linux-aarch64.so.1, 
BuildID[sha1]=5c383348c76a16fa1ea9270f290d5ae05cb4103a, for GNU/Linux 3.7.0, not stripped
```
The interpreter is no correct if installing from a tzst, which must be `/data/data/com.winlator/files/rootfs/lib/ld-linux-aarch64.so.1,`

**Comment by ksco** [comment]
You can patch the interpreter to whatever it wants, see https://github.com/ptitSeb/box64/blob/main/.github/workflows/release.yml#L320

**Comment by FrontMage** [comment]
[box64-16668-1.txt](https://github.com/user-attachments/files/20720897/box64-16668-1.txt)
@ksco still same issue with 0.3.7

**Comment by ksco** [comment]
![Image](https://github.com/user-attachments/assets/8c0a4b86-828a-42c2-bbcf-5a4b30f7ea50)

So I downloaded this game, registered an account, and it's indeed kept disconnected, but the reason can be complicated, as it's an online game.

**Comment by FrontMage** [comment]
@ksco wine on x86 platform works fine, and on exagear it works, on arm MacOS crossover works, only box64 has this problem
So I suspect it has something to do with the net api handling.

**Comment by Farlike** [comment]
I ask on another private server about this problem. Seems like it's same.
"The problem is that warden doesn't work on Linux, because it doesn't work, the anti-cheat bans you" 
Need to figure out how warden work and force to launch it

**Comment by FrontMage** [comment]
> I ask on another private server about this problem. Seems like it's same. "The problem is that warden doesn't work on Linux, because it doesn't work, the anti-cheat bans you" Need to figure out how warden work and force to launch it

I can confirm it is not linux issue since with x86 wine, it works perfectly fine, and with exagear emulator it also works on android

**Comment by LizardAlex** [comment]
I was able to log in after 10–15 tries. Sometimes it takes many more, but sometimes it lets you in on the first attempt.
Turtle WoW Winlator 10

**Comment by Sioma112233** [comment]
I confirm having same issue.

The game works well on linux+wine without box64, 
And has the "disconnected" symptom when running via box64
