### ISSUE TITLE
[BOX32] (lindbergh) SIGABRT in native libc

### ISSUE THREAD

**Issue by Azkali** [ptitSeb/box64#2969]
Trying to run [lindbergh](https://github.com/lindbergh-loader/lindbergh-loader) on Nintendo Switch running L4T Fedora 42 (kernel version 4.9.140) I get the following problem:

```
./lindbergh
[binfmt_dispatcher] Using box64
[BOX64] Box64 with Dynarec v0.3.4 nogit built on Mar 11 2025 00:00:00
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2
[BOX64] Running on Cortex-A57 with 4 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Counted 43 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/home/az/.local/bin/:/home/az/bin/:/usr/local/bin/:/usr/bin/
[BOX64] Looking for /home/az/After Burner Climax/After Burner Climax/lindbergh
[BOX64] argv[1]="./lindbergh"
[BOX64] argv[2]="./lindbergh"
[BOX32] Using Box32 to load 32bits elf
[BOX32] Memory higher than 32bits reserved
[BOX32] Rename process to "lindbergh"
[BOX32] Using native(wrapped) libm.so.6
[BOX32] Using native(wrapped) libc.so.6
[BOX32] Using native(wrapped) ld-linux.so.2
[BOX32] Using native(wrapped) libpthread.so.0
[BOX32] Using native(wrapped) librt.so.1
[BOX32] Using native(wrapped) libdl.so.2
[BOX32] Warning, pointer 0x7facbcc3c8 is not a 32bits value
[BOX32] NativeBT: /home/az/After Burner Climax/After Burner Climax/lindbergh() [0x3487cdc0]
[BOX32] NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7facc8c6c0]
[BOX32] NativeBT: /usr/lib64/libc.so.6(+0x8efdc) [0x7facaeefdc]
[BOX32] NativeBT: /usr/lib64/libc.so.6(gsignal+0x1c) [0x7faca9b4bc]
[BOX32] NativeBT: /usr/lib64/libc.so.6(abort+0x2c) [0x7faca859c8]
[BOX32] NativeBT: /home/az/After Burner Climax/After Burner Climax/lindbergh() [0x3487acd4]
[BOX32] NativeBT: /home/az/After Burner Climax/After Burner Climax/lindbergh() [0x34e59a60]
[BOX32] NativeBT: [0x1000043c8]
[BOX32] EmulatedBT: box64(dirname+0) [0x308203e0]
[BOX32] EmulatedBT: ??? [0x36fb846040003f3d]
[BOX32] 25907|SIGABRT @0x7facaeefdc (???(/usr/lib64/libc.so.6+0x8efdc)) (x64pc=0x308203f3/"???", rsp=0x3080c38c, stack=0x30010000:0x30810000 own=(nil) fp=0x3080d3c8), for accessing 0x3e800006533 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x400102c540003df3 RSP-0x18:0x0000000000000020 RSP-0x10:0x0000000040003ddf RSP-0x08:0x0000004036fa7e10
RSP+0x00:0x36fb846040003f3d RSP+0x08:0x00000001400102c5 RSP+0x10:0x3080e4ac40003e22 RSP+0x18:0x3080e8ac3080dcac
RAX:0x0000000036fb8460 RCX:0x0000000000000000 RDX:0x000000003080c7c0 RBX:0x0000000040016ee0 
RSP:0x000000003080c38c RBP:0x000000003080d3c8 RSI:0x000000003080f0e0 RDI:0x000000003080d3bc 
 R8:0x0000000000000000  R9:0x0000000000000000 R10:0x0000000000000000 R11:0x0000000000000000 
R12:0x0000000000000000 R13:0x0000000000000000 R14:0x0000000000000000 R15:0x0000000000000000 
ES:0x002b CS:0x0023 SS:0x002b DS:0x002b FS:0x0000 GS:0x0033 
```

**Comment by ksco** [comment]
v0.3.4 is pretty old, please upgrade your Box64 to the latest main and try again.

**Comment by Azkali** [comment]
Thanks, just updated it to the latest main and here is the new issue:

```
[BOX64] Box64 arm64 v0.3.7 c8c707e7 with Dynarec built on Sep  4 2025 18:54:56
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2
[BOX64] Running on Cortex-A57 with 4 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Counted 43 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/home/az/.local/bin/:/home/az/bin/:/usr/local/bin/:/usr/bin/
[BOX64] Looking for ./lindbergh
[BOX64] Box64 arm64 v0.3.7 c8c707e7 with Dynarec built on Sep  4 2025 18:54:56
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2
[BOX64] Running on Cortex-A57 with 4 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Counted 44 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/home/az/.local/bin/:/home/az/bin/:/usr/local/bin/:/usr/bin/
[BOX64] Looking for ./lindbergh
[BOX32] Personality set to 32bits
[BOX32] Using Box32 to load 32bits elf
[BOX32] Memory higher than 32bits reserved
[BOX32] Rename process to "lindbergh"
[BOX32] Using native(wrapped) libm.so.6
[BOX32] Using native(wrapped) libc.so.6
[BOX32] Using native(wrapped) ld-linux.so.2
[BOX32] Using native(wrapped) libpthread.so.0
[BOX32] Using native(wrapped) librt.so.1
[BOX32] Using native(wrapped) libdl.so.2
Auto-detected ELF: abc
[BOX32] Warning, pointer 0x7f8979d708 is not a 32bits value
[BOX32] NativeBT: /usr/local/bin/box64() [0x3482f348]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3486728c]
[BOX32] NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f8985c6c0]
[BOX32] NativeBT: /usr/lib64/libc.so.6(+0x8fdbc) [0x7f896bfdbc]
[BOX32] NativeBT: /usr/lib64/libc.so.6(gsignal+0x1c) [0x7f8966ba3c]
[BOX32] NativeBT: /usr/lib64/libc.so.6(abort+0x2c) [0x7f89655a08]
[BOX32] NativeBT: /usr/local/bin/box64() [0x34869834]
[BOX32] NativeBT: /usr/local/bin/box64() [0x34e0dd50]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3500d7d8]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3483d6fc]
[BOX32] NativeBT: /usr/local/bin/box64(my32___libc_start_main+0x164) [0x3484b754]
[BOX32] NativeBT: /usr/local/bin/box64() [0x34e45d8c]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3500d7d8]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3483d6fc]
[BOX32] NativeBT: /usr/local/bin/box64() [0x348357f8]
[BOX32] NativeBT: /usr/local/bin/box64() [0x3482f178]
[BOX32] NativeBT: /usr/lib64/libc.so.6(+0x2621c) [0x7f8965621c]
[BOX32] NativeBT: /usr/lib64/libc.so.6(__libc_start_main+0x9c) [0x7f896562fc]
[BOX32] NativeBT: /usr/local/bin/box64(_start+0x30) [0x3482f1f0]
[BOX32] EmulatedBT: box64(dirname+0) [0x308113e0]
[BOX32] EmulatedBT: ??? [0x36e31de040003f3d]
[BOX32] 6727|SIGABRT @0x7f896bfdbc (???(/usr/lib64/libc.so.6+0x8fdbc)) (x64pc=0x308113f3/"???", rsp=0x3080c40c, stack=0x30010000:0x30810000 own=(nil) fp=0x3080d448), for accessing 0x3e800001a47 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x400102c540003df3 RSP-0x18:0x0000000000000020 RSP-0x10:0x0000000040003ddf RSP-0x08:0x000000f036e22760
RSP+0x00:0x36e31de040003f3d RSP+0x08:0x00000001400102c5 RSP+0x10:0x3080e52c40003e22 RSP+0x18:0x3080e92c3080d52c
RAX:0x0000000036e31de0 RCX:0x0000000000000000 RDX:0x000000003080c840 RBX:0x0000000040016ee0 
RSP:0x000000003080c40c RBP:0x000000003080d448 RSI:0x000000003080f160 RDI:0x000000003080d43c 
 R8:0x0000000000000000  R9:0x0000000000000000 R10:0x0000000000000000 R11:0x0000000000000000 
R12:0x0000000000000000 R13:0x0000000000000000 R14:0x0000000000000000 R15:0x0000000000000000 
ES:0x002b CS:0x0023 SS:0x002b DS:0x002b FS:0x0000 GS:0x0033 
Aborted (core dumped)
```

**Comment by ksco** [comment]
This should be addressed with the above PR, please try again.

**Comment by Azkali** [comment]
Your PR got me past this issue, unsure of what it is going on after but the "main" issue of not being able to run the emulator is not solved. Will close this issue though as it solved the inital report, thank you !

**Comment by ksco** [comment]
Feel free to open a new ticket with steps to reproduce the main issue!
