### ISSUE TITLE
[BOX64] The latest box64 causes broken game save and rendering of Hades 2

### ISSUE THREAD

**Issue by Opi5KDTP** [ptitSeb/box64#3242]
The game Hades won't load save games, and crash; broken rendering.
I tested on Wine-10.15, Wine-10.20, GE-Proton-10.25

> box64-rk3588/noble,unknown 0.3.9+20251129.555b506-1 arm64 <-- started here
> box64-rk3588/noble,unknown,now 0.3.9+20251128.3059fe2-1 arm64 [installed]
> box64-rk3588/noble 0.3.9+20251127.d5d4cc0-1 arm64

**My Specs:**
Orange Pi 5 (RK3588s)
Armbian 25.8.x - Ubuntu 24.04 Noble
PanVk (mesa 26.0.0~git2511240905.108d2d29a91)

Before:
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/1a5e63d3-60d1-4f45-8ee1-302875306fe0" />

After:
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/c26523c4-d118-4a94-bd68-0bc81639e92c" />

**Comment by ksco** [comment]
I fixed a regression in current latest commit, have you tried that?

**Comment by Opi5KDTP** [comment]
I am using ppa. So, I will wait for the next build and feedback later. Thanks!

**Comment by khanh-it** [comment]
@ksco I have upgraded box64, still the same
> Box64 arm64 v0.3.9 039c6f55 with Dynarec built on Nov 30 2025 07:04:17


<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/9da063e4-a982-4f4e-87be-cf0765209f87" />

**Comment by ptitSeb** [comment]
Unfortunatly, I pushed another fix yesterday about this: 2d2c6a2aa176b2855f016cfc1a3b024941870dd4 so might need another day?

**Comment by Opi5KDTP** [comment]
Lucky me, ppa got pushed

> Box64 arm64 v0.3.9 2d2c6a2a with Dynarec built on Dec  1 2025 07:09:31

I can confirm, it's fixed. Thank you all!

**Comment by ptitSeb** [comment]
Glad everything is fixed!
