### ISSUE TITLE
Regression between 9th and 19th december (game Beyond Good and Evil)

### ISSUE THREAD

**Issue by fafner2000** [ptitSeb/box64#3319]
Hello,

Short story:

Something broke the GOG version of the game Beyond Good and Evil [1] between commits 1c282c2c26778dd99ab8d639e45ec4b2680d8a97 (2025-12-09) and f2660cd3f007bd765873dafb21c8e482ec2b288e (2025-12-19).

I will probably try to find the exact commit where the regression bug is, but I'll have to find some time to do that. However, if in the meantime you have a possible fix, just tell me and I'll make sure to test it.

Long story:

Last 10th december, I installed the GOG version of the game Beyond Good and Evil [1] on a Debian 13 (Trixie) Raspberry PI. At this point the game worked fine with some light performances issues.

I uninstalled both wine and box64 to test hangover. It failed miserably, so I just cleaned up the mess and reinstalled box64 and wine. Total failure: the game still starts and can load games, but there was heavy graphical glitches and often camera positioning issues, as well as unexplained sudden deaths. I finally traced the problem to box64, as uninstalling box64 and reinstalling the version downloaded the 10th right from the system cache fixed everything. Luckily, it hadn't been purged yet; you can be sure that I swiftly made a backup.

I used the application Pi-Apps which automates everything so I don't have to spent hours finding the magic incantations to make things work. However, for some reason, it installs the latest commit available, probably not caring that it might not be an actual release. Given the names of the .deb files involved, I deduced that the regression bug was somewhere between commits 1c282c2c26778dd99ab8d639e45ec4b2680d8a97 (2025-12-09) and f2660cd3f007bd765873dafb21c8e482ec2b288e (2025-12-19). I made a last try today with commit 050e0f9f43dcec2d9b2365056e248ca7b6ff0e03 (2025-12-28) and it still has the same issues.

Note: The game is 32 bits, but the wine version installed on the Raspberry PI is 100% 64 bits and uses some kind of 32 bits emulation similar to what Microsoft Windows does.

[1] https://www.gog.com/en/game/beyond_good_and_evil

**Comment by ptitSeb** [comment]
I don't own this game, so cannot test. Have you tested the game with latest box64? is it still broken? Because the current version seems very stable for me now.

You might need to build box64 from source to really bisect the issue.

(note: this is using Wine+new WOW64 indeed, to stay in 100% 64bit lands, similar to MS Windows)

**Comment by fafner2000** [comment]
Update: I compiled with commit 09bdbcb0490b30d1da70dff420de80c758028676 (latest) and 050e0f9f43dcec2d9b2365056e248ca7b6ff0e03 (the one where I observed a problem), and the problem has disappeared from both. However, I compiled with default options, and the performances are abyssal (less that 1 FPS) and even exiting the game takes something like 1 minute. I'll try to find how to compile with release options.

Edit 1: I suspect that the missing option is -D ARM_DYNAREC=ON
Edit 2: I finally compiled with options "-D RPI5ARM64=1 -D CMAKE_BUILD_TYPE=RelWithDebInfo" (which seems to imply dynarec) and the problem has reappeared with commit 050e0f9f43dcec2d9b2365056e248ca7b6ff0e03.

**Comment by ptitSeb** [comment]
> Update: I compiled with commit [09bdbcb](https://github.com/ptitSeb/box64/commit/09bdbcb0490b30d1da70dff420de80c758028676) (latest) and [050e0f9](https://github.com/ptitSeb/box64/commit/050e0f9f43dcec2d9b2365056e248ca7b6ff0e03) (the one where I observed a problem), and the problem has disappeared from both. However, I compiled with default options, and the performances are abyssal (less that 1 FPS) and even exiting the game takes something like 1 minute. I'll try to find how to compile with release options.
> 
> Edit 1: I suspect that the missing option is -D ARM_DYNAREC=ON Edit 2: I finally compiled with options "-D RPI5ARM64=1 -D CMAKE_BUILD_TYPE=RelWithDebInfo" (which seems to imply dynarec) and the problem has reappeared with commit [050e0f9](https://github.com/ptitSeb/box64/commit/050e0f9f43dcec2d9b2365056e248ca7b6ff0e03).

I guess I have compiled without Dynarec! 
Yeah, see the edit, you found the right parameters.

Now, the bug in on 050e0f9f43dcec2d9b2365056e248ca7b6ff0e03 ok, but is it solved with 09bdbcb0490b30d1da70dff420de80c758028676 ?

**Comment by fafner2000** [comment]
I am compiling this commit right now, it takes forever :-D

**Comment by fafner2000** [comment]
Bug still present on commit 09bdbcb0490b30d1da70dff420de80c758028676.

**Comment by ptitSeb** [comment]
Ah ok. I might buy the game on GoG (it's on sale) and debug on my side. Probably an issue on x87 emulation, it's tricky to debug...

**Comment by fafner2000** [comment]
Bug not present on commit 1c282c2c26778dd99ab8d639e45ec4b2680d8a97.

Edit 1: Tomorrow afternoon I'll have some time to bisect more precisely.
Edit 2: Present on b9a9317a7350e72708923d74158f1a6d52461cec.
Edit 3: Present on 3b9edf00702fdc4588fb66361c913749099a177a.
Edit 4: Present on 57466cf0f031042250ba9e51e1f9330f1b788542.

**Comment by ptitSeb** [comment]
Culprit is eb743a13075a562891dbc2b7585f597200c97e43 wich is a complex commit. I'll work on that tomorrow.

**Comment by ptitSeb** [comment]
I have a fix. I'll do some more testing tomorrow and will push it.

**Comment by ptitSeb** [comment]
Ok, it's fixed for me. You can update box64 and try on your side.

**Comment by g7ruh** [comment]
Thanks for the update, it fixes a problem in PlanePlotter where the graphics is messed up. Checked this morning for any reported issues and arrived here.

The problem:

<img width="407" height="284" alt="Image" src="https://github.com/user-attachments/assets/7ca3ceed-0e6d-49fa-af71-17c7494350f2" />


which displays correctly after compiling the recent update:

<img width="299" height="181" alt="Image" src="https://github.com/user-attachments/assets/20b1d7ae-e8e0-47c0-97ab-f04bcc8c3b26" />

**Comment by ptitSeb** [comment]
Thanks for reporting this @g7ruh :)

**Comment by fafner2000** [comment]
Fixed on my side too.

I have other games that have subtle (or sometimes no so subtle) bugs, is there some built-in utility that I can use to attempt to examine how box64 recompile them ?

**Comment by ptitSeb** [comment]
> Fixed on my side too.
> 
> I have other games that have subtle (or sometimes no so subtle) bugs, is there some built-in utility that I can use to attempt to examine how box64 recompile them ?

Sure. I suggest you build box64 with trace (with `HAVE_TRACE` on cmake). You will need ZyDis to build but it will enhance the output.

Then you create a profile or dirrectly on command line you add `BOX64_DYNAREC_DUMP=2` and `BOX64_TRACE=0-1` to output the full conversion. Also use `BOX64_TRACE_FILE=/path/to/dump.txt` to output to a text file directly. (use `less -R /path/to/dump.txt` to read the dump with color (or use `BOX64_DYNAREC_DUMP=1` to avoid the use of color, but it's much more readable with!).
