### ISSUE TITLE
Clone Hero log (missing implementations)

### ISSUE THREAD

**Issue by coreybruce** [ptitSeb/box64#50]
```
[corey@corey-pi4 ~]$ clonehero
Replacing old data folder
Replacing old executable
rm: cannot remove '/home/corey/.clonehero/Clone Hero.x86_64': No such file or directory
Box64 with Dynarec v0.1.3 acc3ed8 built on Jul 10 2021 22:20:55
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 51 Env var
Looking for /home/corey/.clonehero/clonehero
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libudev.so.1
Found path: /home/corey/.clonehero/clonehero
Using emulated /home/corey/.clonehero/clonehero_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Error: Global Symbol data_start not found, cannot apply R_X86_64_GLOB_DAT @0xffff91e2c200 ((nil)) in /home/corey/.clonehero/clonehero_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Error: Global Symbol __data_start not found, cannot apply R_X86_64_GLOB_DAT @0xffff91e2c758 ((nil)) in /home/corey/.clonehero/clonehero_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Mono path[0] = '/home/corey/.clonehero/clonehero_Data/Managed'
Mono config path = '/home/corey/.clonehero/clonehero_Data/MonoBleedingEdge/etc'
0x6b915040: Stack is corrupted, aborting
==== CPU Registers ====
RAX=cf918d1595e23700 RCX=ffffffffffffffff RDX=0000ffffad21bab0 RBX=0000ffffad21ba20 RSP=0000ffffad21ba08 FLAGS=--S--PC
RBP=0000ffffad21bab8 RSI=0000ffffad21bab8 RDI=0000ffffad21ba20  R8=0000000000000000  R9=0000000000000010 
R10=0000000000001000 R11=0000000000001000 R12=0000ffffad21bab0 R13=00000000018e51ec R14=0000ffffad21bb08 
R15=000000000206efa0 RIP=000000006ba824f3 
======== Stack ========
Stack is from FFFFAD21BAB8 to FFFFAD21BA08
Old IP: 6B915040
Library libXrender.so.1 (0x6be87a20) needs 0x6be87190, but it was not found. Ignoring.
Library libXext.so.6 (0x6be72e10) needs 0x6be9a880, but it was not found. Ignoring.
Library libXext.so.6 (0x6be72e10) needs 0x6be87190, but it was not found. Ignoring.
Library libXext.so.6 (0x6be72e10) needs 0x6be8b630, but it was not found. Ignoring.
Library libXext.so.6 (0x6be72e10) needs 0x6be77890, but it was not found. Ignoring.
Library libX11.so.6 (0x6be6fb40) needs 0x6be9a880, but it was not found. Ignoring.
Library libX11.so.6 (0x6be6fb40) needs 0x6be87190, but it was not found. Ignoring.
Library libX11.so.6 (0x6be6fb40) needs 0x6be8b630, but it was not found. Ignoring.
Library libX11.so.6 (0x6be6fb40) needs 0x6be77890, but it was not found. Ignoring.
Library libc.so.6 (0x6ba27450) needs 0x6c523d40, but it was not found. Ignoring.
Library libgcc_s.so.1 (0x6ba1b7d0) needs 0x6c523d40, but it was not found. Ignoring.
Library ld-linux-x86-64.so.2 (0x6ba27690) needs 0x6c523d40, but it was not found. Ignoring.
Library libpthread.so.0 (0x6ba26330) needs 0x6c523d40, but it was not found. Ignoring.
Library libm.so.6 (0x6ba1a650) needs 0x6c523d40, but it was not found. Ignoring.
Library librt.so.1 (0x6b954c80) needs 0x6c523d40, but it was not found. Ignoring.
Library libdl.so.2 (0x6b9539a0) needs 0x6c523d40, but it was not found. Ignoring.
Stop waiting for remaining thread 120813
120813|0x6ba2e000: Unimplemented Opcode (00) F0 CF 5D 6C 00 00 00 00 F0 0F 5E 6C 00 00 00
```

**Comment by ptitSeb** [comment]
The missing symbols are not a the cuase of the error. The "Stack corruption" is the issue. As the game is free, I'll check on my side if I can reproduce and fix the issue.

**Comment by coreybruce** [comment]
Ahh My bad, I hope I am helping to improve and debug any issues with Box64 because I think it's a really awesome project.

**Comment by mogery** [comment]
If you're using libc >=2.33 (Ubuntu >=21.04), this is probably fixed by #135. Could you try pulling my branch and testing it?

```bash
git clone https://github.com/mogery/box64
cd box64
git checkout getattr-align-wrap
# follow further build instructions for your platform
```

**Comment by cidkidnix** [comment]
Clonehero works fine on my machine on commit dfd2a4ef0e236b5e043ef5b5bf1e16791dec3dd7

```
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            cidkid@ganymede 
          ▜███▙       ▜███▙  ▟███▛            --------------- 
           ▜███▙       ▜███▙▟███▛             OS: NixOS 23.11pre-git (Tapir) aarch64 
            ▜███▙       ▜██████▛              Host: ADLINK Ampere Altra Developer Platform 
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.5.9 
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 31 mins 
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 1246 (nix-system), 1639 (nix-user) 
          ▟███▛             ▜██▛ ▟███▛        Shell: zsh 5.9 
         ▟███▛               ▜▛ ▟███▛         Resolution: 3440x1440 
▟███████████▛                  ▟██████████▙   WM: i3 
▜██████████▛                  ▟███████████▛   Theme: adw-gtk3 [GTK2/3] 
      ▟███▛ ▟▙               ▟███▛            Terminal: kitty 
     ▟███▛ ▟██▙             ▟███▛             Terminal Font: DejaVu Sans Mono 10.0 
    ▟███▛  ▜███▙           ▝▀▀▀▀              CPU: (96) @ 2.800GHz 
    ▜██▛    ▜███▙ ▜██████████████████▛        GPU: NVIDIA GeForce RTX 4090 
     ▜▛     ▟████▙ ▜████████████████▛         Memory: 17667MiB / 96082MiB 
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙                                      
         ▟███▛  ▜███▙       ▜███▙                                     
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
         ```

**Comment by coreybruce** [comment]
Hey sorry for leaving this issue open for so long and not replying, I am still having issues but this time I am on my Raspberry pi 5 with version 0.2.8-1 but with a different issue

```
[corey@corey-pi5 ~]$ clonehero
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:16384 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 69 entries
Box64 with Dynarec v0.2.8 44f2608 built on Jun 17 2024 05:16:19
BOX64: Detected 48bits at least of address space
Counted 42 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/:/usr/lib/rustup/bin/
Looking for /opt/clonehero/clonehero
Rename process to "clonehero"
Using emulated /opt/clonehero/UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Using native(wrapped) libdbus-1.so.3
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libudev.so.1
```

**Comment by rajdakin** [comment]
There is no error in the log you provided, only debug information.

**Comment by ptitSeb** [comment]
That's a Unity3D game. Did you used `MESA_GL_VERSION_OVERRIDE=3.2` to launch the game? Else, it will just fail because openGL doesn't provide hight enough context...

**Comment by coreybruce** [comment]
Ahh I see, well I tried that and it just fails to run

```
clonehero MESA_GL_VERSION_OVERRIDE=3.2
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:16384 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 69 entries
Box64 with Dynarec v0.2.8 44f2608 built on Jun 17 2024 05:16:19
BOX64: Detected 48bits at least of address space
Counted 42 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/:/usr/lib/rustup/bin/
Looking for /opt/clonehero/clonehero
argv[1]="MESA_GL_VERSION_OVERRIDE=3.2"
Rename process to "clonehero"
Using emulated /opt/clonehero/UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Using native(wrapped) libdbus-1.so.3
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libudev.so.1
```

**Comment by ptitSeb** [comment]
That this other way around:

```bash
MESA_GL_VERSION_OVERRIDE=3.2 clonehero
```

**Comment by ptitSeb** [comment]
Also, I've just released v0.3.0 so you might want to update your box64 version.

**Comment by coreybruce** [comment]
Ok I'll give that a try :+1: 

Thanks for letting me know, I am currently using the repo package on Manjaro Arm64 but I could try compiling it as a test before they update the package.
